### ISSUE TITLE
【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据

### ISSUE THREAD

**Issue by gradient30** [smart-test-ti/SoloX#101]
试用了一下sonic的这个插件 是可以正常获取各类游戏的fps的（已偿试过安卓7~12不同品牌的设备），可以参考一下哈
https://github.com/SonicCloudOrg/sonic-android-supply

命令行可以打印出来 sonic-android-supply.exe perfmon -p 包名 -s 设备序列号

**Comment by rafa0128** [comment]
> 试用了一下sonic的这个插件 是可以正常获取各类游戏的fps的（已偿试过安卓7~12不同品牌的设备），可以参考一下哈 https://github.com/SonicCloudOrg/sonic-android-supply
> 
> 命令行可以打印出来 sonic-android-supply.exe perfmon -p 包名 -s 设备序列号

好像这个工程没看到可执行文件 sonic-android-supply.exe

**Comment by rafa0128** [comment]
![image](https://user-images.githubusercontent.com/24454096/220028732-bcf4b759-cb54-45ed-975e-0d23cfe9875a.png)

看了他的源码，应该和solox一样的，如果他的可以就很奇怪了

**Comment by gradient30** [comment]
这个在他们官方的发布版本包里https://sonic-cloud.cn/deploy/agent-deploy.html





SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101)





  
试用了一下sonic的这个插件 是可以正常获取各类游戏的fps的（已偿试过安卓7~12不同品牌的设备），可以参考一下哈 https://github.com/SonicCloudOrg/sonic-android-supply
 
命令行可以打印出来 sonic-android-supply.exe perfmon -p 包名 -s 设备序列号
  
好像这个工程没看到可执行文件 sonic-android-supply.exe

**Comment by gradient30** [comment]
正好搭建Sonic这个公共平台，正好发现他们提供了这个性能测试 去试了下，确实可以（还修复了不少低版本兼容的问题）




SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101)





 

 
看了他的源码，应该和solox一样的，如果他的可以就很奇怪了

**Comment by rafa0128** [comment]
> 正好搭建Sonic这个公共平台，正好发现他们提供了这个性能测试 去试了下，确实可以（还修复了不少低版本兼容的问题） SunTM&amp;R ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "smart-test-ti/SoloX" ***@***.***&gt;; 发送时间:&nbsp;2023年2月20日(星期一) 下午2:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101) 看了他的源码，应该和solox一样的，如果他的可以就很奇怪了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我找时间测试下，正好这段时间要加功能，全面抄perfdog

**Comment by gradient30** [comment]
我擦 好期待，干趴perfdog
^0^


SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101)





  
正好搭建Sonic这个公共平台，正好发现他们提供了这个性能测试 去试了下，确实可以（还修复了不少低版本兼容的问题） SunTM&amp;R @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "smart-test-ti/SoloX" @.&gt;; 发送时间:&nbsp;2023年2月20日(星期一) 下午2:28 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101) 看了他的源码，应该和solox一样的，如果他的可以就很奇怪了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我找时间测试下，正好这段时间要加功能，全面抄perfdog

**Comment by rafa0128** [comment]
![image](https://user-images.githubusercontent.com/24454096/221141201-63d53fa8-5654-4e34-89c7-5741d1b676d5.png)

我试过sonic了一样会有问题的，我看过代码就是用adb去获取的，只要通过adb就会有这个问题，因为不同设备它surfaceFlinger不一定及时返回数据的

**Comment by rafa0128** [comment]
perfdog没有这个问题应该是通过api去获取的

**Comment by rafa0128** [comment]
> 正好搭建Sonic这个公共平台，正好发现他们提供了这个性能测试 去试了下，确实可以（还修复了不少低版本兼容的问题） SunTM&amp;R ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "smart-test-ti/SoloX" ***@***.***&gt;; 发送时间:&nbsp;2023年2月20日(星期一) 下午2:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101) 看了他的源码，应该和solox一样的，如果他的可以就很奇怪了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

基本没有做什么兼容，看了代码sonic给性能的收集写的东西还是比较少的

**Comment by ZhouYixun** [comment]
你开发者开了gfxinfo了吗？

**Comment by gradient30** [comment]
都开了的，这边所有手机都会默认去打开一下


SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月1日(星期三) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] 【建议】关于采集手游app的fps的方法，建议可以参考下sonic的 试用过一些设备均可采集游戏app的性能数据 (Issue #101)





 
你开发者开了gfxinfo了吗？
