### ISSUE TITLE
iOS 无法收集网络数据

### ISSUE THREAD

**Issue by cunzhegao** [smart-test-ti/SoloX#109]
SoloX 版本：2.4.1
设备：iPhone 13 Pro
OS：16.0.2

Network Data 栏都是 0，看 terminal 有疑似报错：

Exception in thread perf:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/solox/public/iosperf/_perf.py", line 266, in append_data
    for _type, data in idata:
  File "/usr/local/lib/python3.11/site-packages/solox/public/iosperf/_perf.py", line 259, in iter_network_flow
    "downFlow": (nstat['rx.bytes'] or 0) / 1024,
KeyError: 'rx.bytes'

**Comment by rafa0128** [comment]
> SoloX 版本：2.4.1 设备：iPhone 13 Pro OS：16.0.2
> 
> Network Data 栏都是 0，看 terminal 有疑似报错：
> 
> Exception in thread perf: Traceback (most recent call last): File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner self.run() File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.11/site-packages/solox/public/iosperf/_perf.py", line 266, in append_data for _type, data in idata: File "/usr/local/lib/python3.11/site-packages/solox/public/iosperf/_perf.py", line 259, in iter_network_flow "downFlow": (nstat['rx.bytes'] or 0) / 1024, KeyError: 'rx.bytes'

请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的

**Comment by cunzhegao** [comment]
> 
> 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的

每次都是一样的问题，试了 2.3.8 也是一样。你正常的 iOS 版本是多少的。

**Comment by cunzhegao** [comment]
> 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。

**Comment by cunzhegao** [comment]
> 
> 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的

试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。
可能是什么问题呢？

**Comment by rafa0128** [comment]
> > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> 
> 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？

ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。

**Comment by cunzhegao** [comment]
> > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > 
> > 
> > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> 
> ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。

iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？

**Comment by rafa0128** [comment]
> > > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > > 
> > > 
> > > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> > 
> > 
> > ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。
> 
> iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？

都会有问题，你的移动设备是wifi还是数据网络？

**Comment by cunzhegao** [comment]
> > > > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > > > 
> > > > 
> > > > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> > > 
> > > 
> > > ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。
> > 
> > 
> > iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？
> 
> 都会有问题，你的移动设备是wifi还是数据网络？

wifi 和数据网络都试过，一样的问题。

**Comment by rafa0128** [comment]
> > > > > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > > > > 
> > > > > 
> > > > > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> > > > 
> > > > 
> > > > ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。
> > > 
> > > 
> > > iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？
> > 
> > 
> > 都会有问题，你的移动设备是wifi还是数据网络？
> 
> wifi 和数据网络都试过，一样的问题。

我现在还不确定是xcode版本还是iphone的兼容性，看报错应该是xcode的instruments没有返回这个数据，你能换台设备试试吗？我这边是没有问题的，iphonex 16.1。我建议如果能看源码提交pr是最好。作者的设备没问题的一律不解决了，等别人提交pr。

**Comment by cunzhegao** [comment]
> > > > > > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > > > > > 
> > > > > > 
> > > > > > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> > > > > 
> > > > > 
> > > > > ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。
> > > > 
> > > > 
> > > > iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？
> > > 
> > > 
> > > 都会有问题，你的移动设备是wifi还是数据网络？
> > 
> > 
> > wifi 和数据网络都试过，一样的问题。
> 
> 我现在还不确定是xcode版本还是iphone的兼容性，看报错应该是xcode的instruments没有返回这个数据，你能换台设备试试吗？我这边是没有问题的，iphonex 16.1。我建议如果能看源码提交pr是最好。作者的设备没问题的一律不解决了，等别人提交pr。

请问你那边 macos 系统是多少的

**Comment by jialeigd** [comment]
报错问题和题主的一样，打日志感觉是返回的nstat数据里没有rx.bytes这个字段了。
日志如下solox iter_network_flow  nstat : {'connection-detected': {'Local': '[fe80::b8ea:cbff:fe08:3432]:58054', 'Remote': '[::]:0', 'InterfaceIndex': 9, 'Pid': -2, 'RecvBufferSize': 131072, 'RecvBufferUsed': 0, 'SerialNumber': 8, 'Protocol': 'tcp6'}}
SoloX 版本：2.4.4
设备：iPhone 6s Plus
OS：15.7

**Comment by rafa0128** [comment]
> 报错问题和题主的一样，打日志感觉是返回的nstat数据里没有rx.bytes这个字段了。 日志如下solox iter_network_flow nstat : {'connection-detected': {'Local': '[fe80::b8ea:cbff:fe08:3432]:58054', 'Remote': '[::]:0', 'InterfaceIndex': 9, 'Pid': -2, 'RecvBufferSize': 131072, 'RecvBufferUsed': 0, 'SerialNumber': 8, 'Protocol': 'tcp6'}} SoloX 版本：2.4.4 设备：iPhone 6s Plus OS：15.7

我没有iphone调试了，你pip install tidevice==0.9.7再试试，我看看是不是tidevice升级后的影响

**Comment by rafa0128** [comment]
> > > > > > > > 请问重新连接收集还有这个问题吗？还是每次都会有，我自己测试是正常的
> > > > > > > 
> > > > > > > 
> > > > > > > 试了下 Android 也是 FPS 和网络数据都是一直 0，不过 Android 没有上面的报错。 可能是什么问题呢？
> > > > > > 
> > > > > > 
> > > > > > ios大概知道什么原因了，是instruments的原因，还在想怎么处理。安卓的fps游戏类app目前收集不了，其他的app需要是动态页面fps才可能不为0，网络应该没啥问题。
> > > > > 
> > > > > 
> > > > > iOS 需要等修复版本嘛？我这边可不可以 fallback 回某个没问题的版本？
> > > > 
> > > > 
> > > > 都会有问题，你的移动设备是wifi还是数据网络？
> > > 
> > > 
> > > wifi 和数据网络都试过，一样的问题。
> > 
> > 
> > 我现在还不确定是xcode版本还是iphone的兼容性，看报错应该是xcode的instruments没有返回这个数据，你能换台设备试试吗？我这边是没有问题的，iphonex 16.1。我建议如果能看源码提交pr是最好。作者的设备没问题的一律不解决了，等别人提交pr。
> 
> 请问你那边 macos 系统是多少的

应该和系统无关，你能指定装pip install tidevice==0.9.7，看看是不是正常

**Comment by jialeigd** [comment]
> 

大神，我怀疑可能是M1返回的数据包不一样了？
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/5088304/224663638-dcf942f5-14ba-4946-bc3b-b8cbae3a5995.png">
如图日志，获取网络数据前几个connection-detected包里没有RxBytes等数据，导致_perf.py里"downFlow": (nstat['rx.bytes'] or 0) / 1024  解析rx.bytes失败，当前获取网络进程崩溃了？

**Comment by jialeigd** [comment]
> > 
> 
> 大神，我怀疑可能是M1返回的数据包不一样了？ <img alt="image" width="1168" src="https://user-images.githubusercontent.com/5088304/224663638-dcf942f5-14ba-4946-bc3b-b8cbae3a5995.png"> 如图日志，获取网络数据前几个connection-detected包里没有RxBytes等数据，导致_perf.py里"downFlow": (nstat['rx.bytes'] or 0) / 1024 解析rx.bytes失败，当前获取网络进程崩溃了？

connection-update包里有RxBytes，TxBytes等数据，大神，在解析里做个容错是不是就可以了？

**Comment by rafa0128** [comment]
> > > 
> > 
> > 
> > 大神，我怀疑可能是M1返回的数据包不一样了？ <img alt="image" width="1168" src="https://user-images.githubusercontent.com/5088304/224663638-dcf942f5-14ba-4946-bc3b-b8cbae3a5995.png"> 如图日志，获取网络数据前几个connection-detected包里没有RxBytes等数据，导致_perf.py里"downFlow": (nstat['rx.bytes'] or 0) / 1024 解析rx.bytes失败，当前获取网络进程崩溃了？
> 
> connection-update包里有RxBytes，TxBytes等数据，大神，在解析里做个容错是不是就可以了？

不是，这个是因为tidevices改了，你先按照我说的pip install tidevice==0.9.7看看是不是正常

**Comment by rafa0128** [comment]
请安装最新版本，我刚发布了
