### ISSUE TITLE
Mac installation and execution details

### ISSUE THREAD

**Issue by pushpeshkarki** [smart-test-ti/SoloX#11]
Can we add how to install the solox on Mac machines and how to run the same?

**Comment by rafa0128** [comment]
> Can we add how to install the solox on Mac machines and how to run the same?

1、Install: pip3 install  -m U solox
2、run: python3 -m solox

**Comment by pushpeshkarki** [comment]
Thanks for the help

**Comment by rafa0128** [comment]
> How to install and use in Windows / Linux? Please help

Please read readme carefully
