### ISSUE TITLE
【BUG】V2.4.1 realme C33（Android 12）和 华为Mate20 采集不到FPS

### ISSUE THREAD

**Issue by luohong** [smart-test-ti/SoloX#111]
![image](https://user-images.githubusercontent.com/983775/223030590-75b77b0e-f9d1-4263-a902-cd4e43f037d8.png)

**Comment by luohong** [comment]
adb shell dumpsys activity activities | grep mResumedActivity

@rafa0128 可以通过以上命令获取 get_focus_activity

**Comment by rafa0128** [comment]
你更新最新版还不行吗？

**Comment by luohong** [comment]
还是不行 2.4.7，还有这里多余

![image](https://user-images.githubusercontent.com/983775/225332685-5b92221e-9dc5-4a6f-8367-7e2460c4e5d0.png)

**Comment by rafa0128** [comment]
> 还是不行 2.4.7，还有这里多余
> 
> ![image](https://user-images.githubusercontent.com/983775/225332685-5b92221e-9dc5-4a6f-8367-7e2460c4e5d0.png)

这里不是个方法，我弄错了，2.4.9试试，我自己的华为设备是可以的
![d3aacfeb6f50bae13ccf7ac35fa2f69](https://user-images.githubusercontent.com/24454096/225486836-e666403e-7797-465b-8241-2761b9ddc4c4.png)
