### ISSUE TITLE
手机或者平板播放爱奇艺视频，fps监控一直为0

### ISSUE THREAD

**Issue by qwz160** [smart-test-ti/SoloX#112]
手机或者平板播放爱奇艺视频，fps监控一直为0
![report](https://user-images.githubusercontent.com/37300037/223669859-331c85f8-a755-4fd9-8cad-d8d4d8b62107.png)

**Comment by rafa0128** [comment]
之前试了一些视频播放器的app是可以的，但是也和机型有关，收集不到就关掉surfaceview，打开gpxinfo试试

**Comment by rafa0128** [comment]
> 手机或者平板播放爱奇艺视频，fps监控一直为0 ![report](https://user-images.githubusercontent.com/37300037/223669859-331c85f8-a755-4fd9-8cad-d8d4d8b62107.png)

建议安卓用原生系统测试，有条件的话专门用pixel来做测试

**Comment by EnjoY1024** [comment]
> gpxinfo
 gpxinfo
怎么打开呀

**Comment by qianhongyang** [comment]
> > 手机或者平板播放爱奇艺视频，fps监控一直为0 ![report](https://user-images.githubusercontent.com/37300037/223669859-331c85f8-a755-4fd9-8cad-d8d4d8b62107.png)
> 
> 建议安卓用原生系统测试，有条件的话专门用pixel来做测试

这里还有个问题是mem渲染不出来，因为存在重复的日期，在analysis.html里加上
`function DuplicateRemoval(arrObj) {
            let map = new Map();
            for (let item of arrObj) {
                map.set(item.x, item);
            }
            return [...map.values()]
        }`
然后在ApexCharts渲染的时候，使用
`if (platform === 'Android') {
                        mem_chart.updateSeries([{
                            name: 'total',
                            data: DuplicateRemoval(data['memTotalData'])
                        }, {
                            name: 'native',
                            data: DuplicateRemoval(data['memNativeData'])
                        }, {
                            name: 'dalvik',
                            data: DuplicateRemoval(data['memDalvikData'])
                        }])
                    } else {
                        mem_chart.updateSeries([{
                            name: 'total',
                            data: DuplicateRemoval(data['memTotalData'])
                        }])
                    }`
去重掉日期一样的数据

**Comment by rafa0128** [comment]
> > gpxinfo
> > gpxinfo
> > 怎么打开呀

手机开发者里面

**Comment by rafa0128** [comment]
> > > 手机或者平板播放爱奇艺视频，fps监控一直为0 ![report](https://user-images.githubusercontent.com/37300037/223669859-331c85f8-a755-4fd9-8cad-d8d4d8b62107.png)
> > 
> > 
> > 建议安卓用原生系统测试，有条件的话专门用pixel来做测试
> 
> 这里还有个问题是mem渲染不出来，因为存在重复的日期，在analysis.html里加上
> 
> ```
> function DuplicateRemoval(arrObj) {
>             let map = new Map();
>             for (let item of arrObj) {
>                 map.set(item.x, item);
>             }
>             return [...map.values()]
>         }
> 然后在ApexCharts渲染的时候，使用
> `if (platform === 'Android') {
>                         mem_chart.updateSeries([{
>                             name: 'total',
>                             data: DuplicateRemoval(data['memTotalData'])
>                         }, {
>                             name: 'native',
>                             data: DuplicateRemoval(data['memNativeData'])
>                         }, {
>                             name: 'dalvik',
>                             data: DuplicateRemoval(data['memDalvikData'])
>                         }])
>                     } else {
>                         mem_chart.updateSeries([{
>                             name: 'total',
>                             data: DuplicateRemoval(data['memTotalData'])
>                         }])
>                     }`
> 去重掉日期一样的数据
> ```

嗯，没想到收集这么快，同一秒能收集两次，写数据的时候限制一下延迟一秒就行了

**Comment by qwz160** [comment]
我分享一下包，感觉获取的所有数据都是不准确的。链接：https://pan.baidu.com/s/1a8qJCVKDQ-HG9RYmjGFNsw?pwd=1314 
提取码：1314 
--来自百度网盘超级会员V7的分享

**Comment by rafa0128** [comment]
> > 
> 
> 是GPU调试层吗

GPU呈现模式分析-在adb shell dumpsys gfxinfo

**Comment by rafa0128** [comment]
> 我分享一下测试包，感觉获取的所有监控数据都是不准确的。链接：https://pan.baidu.com/s/1a8qJCVKDQ-HG9RYmjGFNsw?pwd=1314 提取码：1314 --来自百度网盘超级会员V7的分享

fps不是很好搞，不要抱太大希望了，现在的fps只是屏幕的刷新率，我目前也只测出很小部分的视频播放器（mxplayer这类型的）是正常的，用的还是谷歌原生系统的设备。其他的指标要是有问题就指出来，迭代比较久了。应该没太大问题，先去看这些指标的文档说明怎么计算的先。

**Comment by rafa0128** [comment]
> 我分享一下测试包，感觉获取的所有监控数据都是不准确的。链接：https://pan.baidu.com/s/1a8qJCVKDQ-HG9RYmjGFNsw?pwd=1314 提取码：1314 --来自百度网盘超级会员V7的分享

fps不是很好搞，不要抱太大希望了，现在的fps只是屏幕的刷新率，我目前也只测出很小部分的视频播放器（mxplayer这类型的）是正常的，用的还是谷歌原生系统的设备。其他的指标要是有问题就指出来，迭代比较久了。应该没太大问题，先去看这些指标的文档说明怎么计算的先。

**Comment by rafa0128** [comment]
可以多换换其他设备试试，建议不要用华为，如果能拿到pixel这种原生系统的手机更好。如果app的界面大部分是静态的基本上fps就是0了

**Comment by qianhongyang** [comment]
> 

确实存在此现象，拿腾讯视频举例，正在播放视频操作的情况下，命令行执行adb shell dumpsys gfxinfo  com.tencent.qqlive收集到数据如图

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/27986405/223978761-444e44bd-c556-4f08-a6f0-c68a90028495.png">

但是solox收集不到fps数据，debug后发现

因为有些app自定义的activity会加标号，在fps.py第382行，会判断当前的activity
比如腾讯视频播放界面加了标号，但是gfxinfo获取的Window不带标号

<img width="694" alt="image" src="https://user-images.githubusercontent.com/27986405/223979869-e4a45073-8e7d-477f-9b51-56337bc203a0.png">
<img width="980" alt="image" src="https://user-images.githubusercontent.com/27986405/223978540-b8c2d7b5-6817-49d3-a467-6fa4bcb8c2c6.png">
<img width="907" alt="image" src="https://user-images.githubusercontent.com/27986405/223979439-dd0ae338-0e0f-437c-9105-7d87958129f0.png">
导致直接continue过，后续逻辑未执行收集不到数据

试了多款app，开了gfxinfo收集不到信息，基本是因为activity带了标号，所以修改为

<img width="931" alt="image" src="https://user-images.githubusercontent.com/27986405/223981435-63a4ace9-ee2b-4167-9d26-022bcd98bc1c.png">


成功获取fps！
![image](https://user-images.githubusercontent.com/27986405/223981145-9b7b3f39-8fcb-4666-8ec9-948d7ce73926.png)

**Comment by rafa0128** [comment]
> > 
> 
> 确实存在此现象，拿腾讯视频举例，正在播放视频操作的情况下，命令行执行adb shell dumpsys gfxinfo com.tencent.qqlive收集到数据如图
> 
> <img alt="image" width="1336" src="https://user-images.githubusercontent.com/27986405/223978761-444e44bd-c556-4f08-a6f0-c68a90028495.png">
> 
> 但是solox收集不到fps数据，debug后发现
> 
> 因为有些app自定义的activity会加标号，在fps.py第382行，会判断当前的activity 比如腾讯视频播放界面加了标号，但是gfxinfo获取的Window不带标号
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/27986405/223979869-e4a45073-8e7d-477f-9b51-56337bc203a0.png">
> 
> <img alt="image" width="980" src="https://user-images.githubusercontent.com/27986405/223978540-b8c2d7b5-6817-49d3-a467-6fa4bcb8c2c6.png">
> 
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/27986405/223979439-dd0ae338-0e0f-437c-9105-7d87958129f0.png">
> 
> 导致直接continue过，后续逻辑未执行收集不到数据
> 试了多款app，开了gfxinfo收集不到信息，基本是因为activity带了标号，所以修改为
> 
> <img alt="image" width="931" src="https://user-images.githubusercontent.com/27986405/223981435-63a4ace9-ee2b-4167-9d26-022bcd98bc1c.png">
> 
> 成功获取fps！ ![image](https://user-images.githubusercontent.com/27986405/223981145-9b7b3f39-8fcb-4666-8ec9-948d7ce73926.png)

我之前加surfaceview没注意这里，帮忙提个pr

**Comment by qianhongyang** [comment]
> > > 
> > 
> > 
> > 确实存在此现象，拿腾讯视频举例，正在播放视频操作的情况下，命令行执行adb shell dumpsys gfxinfo com.tencent.qqlive收集到数据如图
> > <img alt="image" width="1336" src="https://user-images.githubusercontent.com/27986405/223978761-444e44bd-c556-4f08-a6f0-c68a90028495.png">
> > 但是solox收集不到fps数据，debug后发现
> > 因为有些app自定义的activity会加标号，在fps.py第382行，会判断当前的activity 比如腾讯视频播放界面加了标号，但是gfxinfo获取的Window不带标号
> > <img alt="image" width="694" src="https://user-images.githubusercontent.com/27986405/223979869-e4a45073-8e7d-477f-9b51-56337bc203a0.png">
> > <img alt="image" width="980" src="https://user-images.githubusercontent.com/27986405/223978540-b8c2d7b5-6817-49d3-a467-6fa4bcb8c2c6.png">
> > <img alt="image" width="907" src="https://user-images.githubusercontent.com/27986405/223979439-dd0ae338-0e0f-437c-9105-7d87958129f0.png">
> > 导致直接continue过，后续逻辑未执行收集不到数据
> > 试了多款app，开了gfxinfo收集不到信息，基本是因为activity带了标号，所以修改为
> > <img alt="image" width="931" src="https://user-images.githubusercontent.com/27986405/223981435-63a4ace9-ee2b-4167-9d26-022bcd98bc1c.png">
> > 成功获取fps！ ![image](https://user-images.githubusercontent.com/27986405/223981145-9b7b3f39-8fcb-4666-8ec9-948d7ce73926.png)
> 
> 我之前加surfaceview没注意这里，帮忙提个pr

没几行代码  你直接更改吧 哈哈

**Comment by EnjoY1024** [comment]
> 

腾讯视频可以，还是有些获取不到

**Comment by rafa0128** [comment]
> > 
> 
> 腾讯视频可以，还是有些获取不到

麻烦下最新版本再试试，我自己测爱奇艺、腾讯视频都是可以的

**Comment by rafa0128** [comment]
> 车载上面用的，还是一样fps为0 周伟强 ***@***.*** 杭州当虹科技股份有限公司 软件测试工程师 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "smart-test-ti/SoloX" ***@***.***&gt;; 发送时间:&nbsp;2023年3月13日(星期一) 上午9:19 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [smart-test-ti/SoloX] 手机或者平板播放爱奇艺视频，fps监控一直为0 (Issue #112) Closed #112 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以重新建个问题，拉代码自己把surfaceview和gpxinfo的数据发出来看看
