### ISSUE TITLE
android直接调用接口，FPS会走到ios里，这里顺序写反了

### ISSUE THREAD

**Issue by EnjoY1024** [smart-test-ti/SoloX#113]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/24515508/224209891-dda2bf04-a532-435c-8e6d-5877f2e25216.png">

**Comment by rafa0128** [comment]
> <img alt="image" width="629" src="https://user-images.githubusercontent.com/24515508/224209891-dda2bf04-a532-435c-8e6d-5877f2e25216.png">

![image](https://user-images.githubusercontent.com/24454096/224212600-c4536ed3-24d7-47c0-b62f-d02de6115189.png)
你是什么时候的代码

**Comment by rafa0128** [comment]
![image](https://user-images.githubusercontent.com/24454096/224212828-92336af8-7c61-45a5-aadb-1526989e6e39.png)
调用的时候，指明参数就行了，不要只写默认

**Comment by EnjoY1024** [comment]
> 

2.4.4  之前版本就是这样调的没问题

> 
走到这里这两个参数就是反的，所以会走到ios里了
<img width="723" alt="image" src="https://user-images.githubusercontent.com/24515508/224214917-ed33031b-a512-40d5-bc3f-ffaa3b5f7560.png">

**Comment by EnjoY1024** [comment]
2.4.4，这个之前这样调用的没有问题，但是现在debug到这里，platform和surfaceview赋值就反了，求联系方式
<img width="666" alt="image" src="https://user-images.githubusercontent.com/24515508/224215799-9a0b949b-473f-40e7-9408-62c951a51ca0.png">

**Comment by rafa0128** [comment]
> 这个之前2.3.0这样调用的没有问题，但是现在debug到这里，platform和surfaceview赋值就反了，求联系方式

嗯，有bug

**Comment by rafa0128** [comment]
apm = APM(pkgName='com.bilibili.app.in',deviceId='ca6bd5a5',platform='Android', surfaceview='true') # surfaceview： false = gpxinfo
