### ISSUE TITLE
win 10 上运行提示此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by byc233518** [smart-test-ti/SoloX#114]
win10 旗舰版
cmd 管理员运行 python -m solox

<img width="1013" alt="企业微信截图_16783522347826" src="https://user-images.githubusercontent.com/13425815/224586176-a068730b-d9d1-4c39-8a72-64e8c4ace518.png">

**Comment by rafa0128** [comment]
> win10 旗舰版 cmd 管理员运行 python -m solox
> 
> <img alt="企业微信截图_16783522347826" width="1013" src="https://user-images.githubusercontent.com/13425815/224586176-a068730b-d9d1-4c39-8a72-64e8c4ace518.png">

自己装下adb吧，配好环境变量，solox自带的adb不适配你的电脑

**Comment by byc233518** [comment]
6
