### ISSUE TITLE
iOS 获取FPS无数据

### ISSUE THREAD

**Issue by jialeigd** [smart-test-ti/SoloX#115]
SoloX 版本：2.4.6
设备：iPhone 12和iPhone 6s plus
OS：14.1和 15.7
python：3.9

【问题：】iOS运行查看FPS图表无数据，打开chrome 调试工具查看有报错，如图
<img width="866" alt="image" src="https://user-images.githubusercontent.com/5088304/224686219-18de9a2b-1da7-4978-865b-2370e1587634.png">
似乎是iOS获取FPS接口少一个参数？导致python里找不到这个接口
<img width="808" alt="image" src="https://user-images.githubusercontent.com/5088304/224686459-8e88e45f-26b3-47b1-8fef-24c1b0666282.png">

**Comment by rafa0128** [comment]
好的，麻烦顺便看看battery那里有问题吗？这个我也是没测过的，有问题我一起改了

**Comment by jialeigd** [comment]
> 好的，麻烦顺便看看battery那里有问题吗？这个我也是没测过的，有问题我一起改了

大神，iOS获取电量似乎也有问题，从可视化界面看不到数据
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/5088304/224870042-a6beccc7-ce14-49a7-93f4-eb843cae7796.png">

设备：iPhone 12  iOS14.1

这个调用apm.collectBattery()接口报错如下： voltage = ioDict['Diagnostics']['IORegistry']['voltage']   KeyError: 'voltage'

打印ioDict如下：ioDict: {'Diagnostics': {'IORegistry': {'AbsoluteCapacity': 1527, 'AdapterDetails': {'AdapterID': 0, 'Current': 2550, 'Description': 'pd charger', 'FamilyCode': -536854521, 'IsWireless': False, 'PMUConfiguration': 2520, 'SerialString': 'UNKNOWN', 'SharedSource': 0, 'Source': 0, 'UsbHvcHvcIndex': 0, 'UsbHvcMenu': [{'Index': 0, 'MaxCurrent': 2550, 'MaxVoltage': 5000}], 'Voltage': 5000, 'Watts': 13}, 'AdapterInfo': 16384, 'Amperage': 1878, 'AppleChargeRateLimitIndex': 0, 'AppleRawAdapterDetails': [{'AdapterID': 0, 'Current': 2550, 'Description': 'pd charger', 'FamilyCode': -536854521, 'IsWireless': False, 'PMUConfiguration': 2520, 'SerialString': 'UNKNOWN', 'SharedSource': 0, 'Source': 0, 'UsbHvcHvcIndex': 0, 'UsbHvcMenu': [{'Index': 0, 'MaxCurrent': 2550, 'MaxVoltage': 5000}], 'Voltage': 5000, 'Watts': 13}, {'AdapterID': 0, 'Current': 0, 'Description': 'batt', 'ErrorFlags': 0, 'IsWireless': False, 'PMUConfiguration': 2520, 'SharedSource': 0, 'Source': 0, 'Voltage': 5000, 'Watts': 0}], 'AppleRawBatteryVoltage': 4166, 'AppleRawCurrentCapacity': 1507, 'AppleRawExternalConnected': True, 'AppleRawMaxCapacity': 2340, 'AtCriticalLevel': False, 'AvgTimeToFull': 222, 'BatteryCellDisconnectCount': 0, 'BatteryData': {'AlgoChemID': 1008582330, 'BatteryHealthMetric': 247, 'CellCurrentAccumulator': [0], 'CellCurrentAccumulatorCount': 0, 'CellVoltage': [4166], 'CellWom': [3224624], 'ChargeAccum': -4262, 'ChemID': 1007901037, 'ChemicalWeightedRa': 214, 'CycleCount': 988, 'DOD0': [8939], 'DailyMaxSoc': 79, 'DailyMinSoc': 20, 'DesignCapacity': 2798, 'FccComp1': 2340, 'FccComp2': 2340, 'FilteredCurrent': 1638, 'FilteredCurrentRc3': 1838, 'FilteredCurrentRc4': 1732, 'Flags': 8320, 'GaugeFlagRaw': 8320, 'GaugeResetCounter': 0, 'ISS': 1833, 'ITMiscStatus': 52283, 'LifetimeData': {'AverageTemperature': 29, 'CycleCountLastQmax': 214, 'MaximumChargeCurrent': 3744, 'MaximumDischargeCurrent': -5063, 'MaximumFCC': 2945, 'MaximumPackVoltage': 4449, 'MaximumQmax': 2952, 'MaximumTemperature': 475, 'MinimumFCC': 1646, 'MinimumPackVoltage': 2549, 'MinimumQmax': 2551, 'MinimumTemperature': -25, 'NCCMax': 2896, 'NCCMin': 2218, 'ResetCnt': 0, 'TemperatureSamples': 74865138, 'TimeAtHighSoc': b'U\x00\x00\x00>\x02\x00\x00o\x01\x00\x00\r\x00\x00\x00\x00\x00\x00\x00>\x00\x00\x00?\x01\x00\x00G\x02\x00\x00U\x00\x00\x00\x00\x00\x00\x00', 'TotalOperatingTime': 20795, 'UpdateTime': 1678758284}, 'ManufactureDate': 61784013680697, 'MaxCapacity': 100, 'MfgData': b'FG904339HDXQ27C2R\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'PMUConfigured': 2520, 'PackCurrentAccumulator': -2791249, 'PackCurrentAccumulatorCount': 490641, 'PassedCharge': -160, 'PresentDOD': [6733], 'Qmax': [2594], 'QmaxDisqualificationReason': 1, 'Qstart': 1018, 'RSS': 138, 'RSSFiltered': 110, 'Ra00': 201, 'Ra01': 264, 'Ra02': 308, 'Ra03': 243, 'Ra04': 235, 'Ra05': 155, 'Ra06': 120, 'Ra07': 153, 'Ra08': 175, 'Ra09': 191, 'Ra10': 237, 'Ra11': 225, 'Ra12': 267, 'Ra13': 586, 'Ra14': 1806, 'RaTableRaw': [b'\x00\xc9\x01\x08\x014\x00\xf3\x00\xeb\x00\x9b\x00x\x00\x99\x00\xaf\x00\xbf\x00\xed\x00\xe1\x01\x0b\x02J\x07\x0e\x00\x00'], 'ResScale': 1000, 'ResetData': b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'ResetDataComms': 0, 'ResetDataFirmware': 0, 'ResetDataHardware': 1, 'ResetDataSoftware': 0, 'ResetDataWatchDog': 0, 'Serial': 'FG904442MH3Q68C3A', 'SimRate': 5076, 'Soc1Voltage': 0, 'StateOfCharge': 64, 'UUID': 269339860, 'Voltage': 4161, 'WeightedRa': 214, 'iMaxAndSocSmoothTable': b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}, 'BatteryInstalled': True, 'BatteryInvalidWakeSeconds': 30, 'BestAdapterIndex': 0, 'BootPathUpdated': 1678267648, 'BootVoltage': 4277, 'CarrierMode': {'CarrierModeHighVoltage': 4100, 'CarrierModeLowVoltage': 3600, 'CarrierModeStatus': 0}, 'ChargerConfiguration': 2520, 'ChargerData': {'ChargerID': 385985337, 'ChargerStatus': 2305844629490778160, 'ChargingCurrent': 2264, 'ChargingVoltage': 4252, 'NotChargingReason': 0, 'VacVoltageLimit': 4340}, 'ChargingOverride': 0, 'CurrentCapacity': 65, 'CycleCount': 988, 'DesignCapacity': 2798, 'ExternalChargeCapable': True, 'ExternalConnected': True, 'FullPathUpdated': 1678757904, 'FullyCharged': False, 'GasGaugeFirmwareVersion': 109050831, 'IOGeneralInterest': 'IOCommand is not serializable', 'IOReportLegend': [{'IOReportChannelInfo': {'IOReportChannelUnit': 0}, 'IOReportChannels': [[7167869599145487988, 6460407809, 'BatteryCycleCount'], [7881712903662169456, 6460407809, 'BatteryMaxTemp'], [7883953708359576944, 6460407809, 'BatteryMinTemp'], [7881713247109672052, 6460407809, 'BatteryMaxPackVoltage'], [7883954051807079540, 6460407809, 'BatteryMinPackVoltage'], [7881713191223763049, 6460407809, 'BatteryChargeCurrent'], [7881713195434927977, 6460407809, 'BatteryDischargeCurrent'], [7881713242914120048, 6460407809, 'BatteryOverChargedCurrent'], [7888177224529174896, 6460407809, 'BatteryOverDischargedCurrent'], [7881712902252946275, 6460407809, 'BatteryMaxFCC'], [7883953706950353763, 6460407809, 'BatteryMinFCC'], [7881713195586841716, 6460407809, 'BatteryMaxDeltaVoltage'], [7883954000284249204, 6460407809, 'BatteryMinDeltaVoltage'], [7809653424000299630, 6460407809, 'BatteryLowAvgCurrentLastRun'], [7521423047848587886, 6460407809, 'BatteryHighAvgCurrentLastRun'], [7881712903612359032, 6460407809, 'BatteryMaxQmax'], [7883953708309766520, 6460407809, 'BatteryMinQMax'], [8173296068204712771, 6460407809, 'BatteryQmaxUpdateSuccessCnt'], [8173296068204709443, 6460407809, 'BatteryQmaxUpdateFailCnt'], [7881712903628337208, 6460407809, 'BatteryMaxRa0-8'], [7883953708325744696, 6460407809, 'BatteryminRa0-8'], [7881712902253732152, 6460407809, 'BatteryMaxRa8'], [7883953706951139640, 6460407809, 'BatteryminRa8'], [7022914058020285808, 6460407809, 'BatteryAvgTemp'], [8387230210786946416, 6460407809, 'BatteryTempSamples'], [8247063023976672884, 6460407809, 'BatteryResetCnt'], [7380400846210821748, 6460407809, 'BatteryFlashWriteCnt'], [8242829161180393076, 6460407809, 'BatteryRDISCnt'], [7167869607987671405, 6460407809, 'BatteryCycleCntLastQmax'], [8390052652791393637, 6460407809, 'BatteryTotalOperatingTime'], [7957688366649270640, 6460407809, 'BatteryNominalChargeCapacity'], [7163086726697609572, 6460407809, 'BatteryChemID'], [7089075284462495847, 6460407809, 'BatteryIDChanged']], 'IOReportGroupName': 'Battery'}], 'IOReportLegendPublic': True, 'InstantAmperage': 1868, 'IsCharging': True, 'KioskMode': {'KioskModeFullChargeVoltage': 4374, 'KioskModeHighSocDays': 0, 'KioskModeHighSocSeconds': 0, 'KioskModeLastHighSocHours': 1, 'KioskModeMode': 1}, 'Location': 0, 'ManufacturerData': b'FG904339HDXQ27C2R\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 'MaxCapacity': 100, 'NominalChargeCapacity': 2265, 'PostChargeWaitSeconds': 120, 'PostDischargeWaitSeconds': 120, 'Serial': 'FG904442MH3Q68C3A', 'Temperature': 4179, 'TimeRemaining': 222, 'UpdateTime': 1678758284, 'UserVisiblePathUpdated': 1678758284, 'VirtualTemperature': 3879, 'Voltage': 4166, 'built-in': True}}, 'Status': 'Success'}

**Comment by rafa0128** [comment]
感谢帮忙测试，自己现在没条件测试了 😅，v2.4.7已经修复

**Comment by jialeigd** [comment]
> 感谢帮忙测试，自己现在没条件测试了 😅，v2.4.7已经修复

感谢大神的工具，感谢soloX团队
