### ISSUE TITLE
android获取fps报错，走到“无法动态获取当前Activity名称，使用page_flip统计全屏帧率！”

### ISSUE THREAD

**Issue by EnjoY1024** [smart-test-ti/SoloX#116]
self.get_focus_activity()的 
adb.shell(cmd='dumpsys SurfaceFlinger | {} {}'.format(d._filterType(), self.package_name), deviceId=self.device)得到的结果没有SurfaceView关键字，返回的activity_name是“"

**Comment by rafa0128** [comment]
这里我放弃兼容了，很多安卓设备返回不太一样，自己拉代码兼容你的设备吧
adb shell -s {deviceid} dumpsys SurfaceFlinger | grep {packagename}，你执行这个发出来看看，surfaceview不行的话，你就用gpxinfo吧，基本不是游戏类app应该都可以

**Comment by EnjoY1024** [comment]
> 这里我放弃兼容了，很多安卓设备返回不太一样，自己拉代码兼容你的设备吧 adb shell -s {deviceid} dumpsys SurfaceFlinger | grep {packagename}，你执行这个发出来看看，surfaceview不行的话，你就用gpxinfo吧，基本不是游戏类app应该都可以
怎么跳过surfaceview，而用gpxinfo呢

**Comment by rafa0128** [comment]
界面不是有个surfaceview开关吗，执行前关掉就行了

**Comment by EnjoY1024** [comment]
> 

想用api获取，发现2.3.0版本的可以获取到，2.4.7fps直接改成2.3.0了 ，谢大佬

**Comment by 1158536658** [comment]
改成false也是报错

**Comment by rafa0128** [comment]
已处理，更新最新版本2.4.8
