### ISSUE TITLE
更新到2.4.8不管开不开surfaceview 开关都只能获取到jank获取不到FPS

### ISSUE THREAD

**Issue by 1158536658** [smart-test-ti/SoloX#117]

**Comment by rafa0128** [comment]
什么app？什么场景测试的

**Comment by rafa0128** [comment]
如果是静态的页面就是为0

**Comment by 1158536658** [comment]
cocox2d游戏，不是静态页面

**Comment by rafa0128** [comment]
不想再说了，不支持游戏

**Comment by rafa0128** [comment]
再解释一下看perfdog的文档也是用surfaceview来计算游戏的帧率的，但是我们通过adb shell dumpsys SurfaceFlinger --latency [LayerName]获取设备的数据都是延迟的，基本上不返回或者比较久才返回，所以没法计算出当前的帧率，这个是adb对不同机器通信的问题，正常来说文档是推荐使用这种方式收集游戏和视频的fps的，但是试了很多机器基本都不行，perfdog可以应该使用了系统级别的api收集的。

**Comment by 1158536658** [comment]
但是我可以用命令在终端能实时获取到啊

**Comment by rafa0128** [comment]
截图看看

**Comment by rafa0128** [comment]
指向layername了没有

**Comment by 1158536658** [comment]
稍等。我一会给你截图

**Comment by rafa0128** [comment]
正常的话刷新返回每次都不一样的数据，应该就可以有值了

**Comment by rafa0128** [comment]
麻烦更新版本再试试，我换了种获取surfaceview activity的方法，我测试抖音、QQ飞车这些居然有数据了
![d3aacfeb6f50bae13ccf7ac35fa2f69](https://user-images.githubusercontent.com/24454096/225486593-4dbd5fd0-dea6-4983-bb12-a9c0f8a0a950.png)

**Comment by rafa0128** [comment]
那估计拿到的数据是这样的
![image](https://user-images.githubusercontent.com/24454096/225546154-4630c865-cee0-45ff-b3cb-bed594f8b9ed.png)
正常这三列的数据都不为0就好了
