### ISSUE TITLE
关于安卓FPS的疑问

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#118]
一、使用SurfaceView方式
官方解释这种方式是可以收集到游戏、视频类应用的FPS的，但是目前试了只发现很少部分视频类APP可以收集到数据，其他基本不行。
看perfdog的文档也是用surfaceview来计算游戏的帧率的，但是我们通过adb shell dumpsys SurfaceFlinger --latency [LayerName]获取设备的数据都是延迟的，基本上不返回或者比较久才返回，所以没法计算出当前的帧率，这个是adb对不同机器通信的问题，perfdog可以应该使用了系统的api收集的。

二、使用gfxinfo方式
界面关掉SurfaceView开关（api则是设置surfaceview=false），手机开发者设置-GPU呈现模式-在adb shell dumpsys gfxinfo中
这种方式不支持游戏的fps，试了大部分视频类app是可以收集到的，但是数据时延迟的，一般不推荐使用这种方式。

**Comment by rafa0128** [comment]
如果明确发现可以收集游戏类的fps的方法，麻烦告知一下solox来调研。

**Comment by rafa0128** [comment]
如果你的机器使用了surfaceview收集没有数据的话，请执行这条命令发出来看看：adb shell dumpsys SurfaceFlinger --list | grep [包名]

**Comment by Nightwish555** [comment]
https://github.com/alipay/SoloPi 可以看看阿里的这个工具，他里面编译好的apk是有游戏fps收集的，不过他官方开源的版本没有fps收集代码，我反编译了apk 是有一个GameFpsTool.java 代码，不过是混淆过的。

**Comment by rafa0128** [comment]
> https://github.com/alipay/SoloPi 可以看看阿里的这个工具，他里面编译好的apk是有游戏fps收集的，不过他官方开源的版本没有fps收集代码，我反编译了apk 是有一个GameFpsTool.java 代码，不过是混淆过的。

这个不用研究了，应该用安卓系统的api就能及时获取surfaceview的数据，adb的通信基本会延迟。想做到和perfdog一样就要实现一个app安装到手机上监听返回性能数据

**Comment by Nightwish555** [comment]
是的，基本要准确获取fps，就需要调用安卓层的api去实时计算，需要懂安卓开发才行。

**Comment by marrash** [comment]
https://github.com/1033866383/perf-orange-cat
這個不曉得有沒有幫助，這個也可以抓到遊戲類型FPS，但不知道怎麼實作的

**Comment by rafa0128** [comment]
> https://github.com/1033866383/perf-orange-cat 這個不曉得有沒有幫助，這個也可以抓到遊戲類型FPS，但不知道怎麼實作的

部分方法引用了solox的，但是核心计算逻辑不一样，试用了感觉应该是准确的，做的很棒啊，能让作者来改造一下solox吗。我已经见底了

**Comment by rafa0128** [comment]
@1033866383 兄弟，能不能邀请你来开发solox，优化它的框架和指标的准确性

**Comment by 1033866383** [comment]
> @1033866383 兄弟，能不能邀请你来开发solox，优化它的框架和指标的准确性

我已经加入solox 项目啦，个人能力有限诚惶诚恐，但是一定会尽力而为希望给项目带来正向的发展。

**Comment by 1033866383** [comment]
> @1033866383 兄弟，能不能邀请你来开发solox，优化它的框架和指标的准确性

我微信f15525730080， 我想加你微信，我找不到你的联系方式。

**Comment by Nightwish555** [comment]
GPU数据 博主调研过没？

**Comment by rafa0128** [comment]
> GPU数据 博主调研过没？

安卓的话，你要通过adb的方式获取，得去找root过的手机

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/pull/222
