### ISSUE TITLE
安卓 7.1.1 获取不到CPU, 内存 数据 

### ISSUE THREAD

**Issue by byc233518** [smart-test-ti/SoloX#119]
请教一下 在一台安卓 7.1.1 PDA 设备上 获取不到CPU, 内存 数据  可能会是哪里问题;

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/13425815/225481170-bd3062e6-0a11-4319-9084-65a323dbf158.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/13425815/225481585-be7f042b-5e3a-4e53-9589-2fd4aab1a71d.png">

同个app 在其他安卓设备上可以获取到数据;
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/13425815/225482077-aa98ec71-e6f2-4073-b11e-653552bff3d0.png">

**Comment by rafa0128** [comment]
会有一定的兼容性，因为每个指标的数据内容还是要靠手机自己写在本地我们用adb去读取，然后计算得出的，数据没写、写的位置不一样、或者格式不一致都有可能，具体得自己调试了

**Comment by rafa0128** [comment]
会有一定的兼容性，因为每个指标的数据内容还是要靠手机自己写在本地我们用adb去读取，然后计算得出的，数据没写、写的位置不一样、或者格式不一致都有可能，具体得自己调试了
