### ISSUE TITLE
【BUG】安卓设备获取fps报错，

### ISSUE THREAD

**Issue by DianMoC** [smart-test-ti/SoloX#121]
问题标题：
【BUG】安卓设备获取fps报错，

问题内容：
操作：通过直接调用接口的方式(只有fps获取报错，其他获取数据均正常)
from solox.public.apm import APM
apm = APM(pkgName='com.vispark.chinese', deviceId='Z81QAEWKMM7BT', platform='Android')
fps = apm.collectFps()  # HZ
print(fps)
[E 230316 17:18:54 fps:309] an exception hanpend in fps _collector_thread , reason unkown!
[D 230316 17:18:54 fps:311] Traceback (most recent call last):
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 279, in _collector_thread
        refresh_period, new_timestamps = self._get_surfaceflinger_frame_data()
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 425, in _get_surfaceflinger_frame_data
        self.focus_window = self.get_huawei_activity()
      File "C:\Install\Anaconda3\lib\site-packages\solox\public\fps.py", line 80, in get_huawei_activity
        activity_name = activity_line_split[2]
    IndexError: list index out of range

请提供：测试机型-魅族17， 系统版本- andriod10；

adb shell dumpsys SurfaceFlinger --list | grep com.vispark.chinese
AppWindowToken{9f73abf token=Token{3f628de ActivityRecord{879019 u0 com.vispark.chinese/.activity.SparkChineseMainActivity t808}}}#0
ffb189 com.vispark.chinese/com.vispark.chinese.activity.SparkChineseMainActivity#0
com.vispark.chinese/com.vispark.chinese.activity.SparkChineseMainActivity#0

**Comment by rafa0128** [comment]
不好搞啊，不同机型adb shell dumpsys SurfaceFlinger --list不一样，只能碰到一个兼容一个了，下个版本我带上吧
你的surfaceview 是这个com.vispark.chinese/com.vispark.chinese.activity.SparkChineseMainActivity#0

**Comment by rafa0128** [comment]
2.5.0已经处理
