### ISSUE TITLE
采集频率怎么调整

### ISSUE THREAD

**Issue by EnjoY1024** [smart-test-ti/SoloX#122]

**Comment by rafa0128** [comment]
api可以调慢，界面不能调整，2秒收集一次（已经是极限了），但是读取计算估计要多跑2秒间隔，如果你的PC机器配置不高可能会更慢。加快的方法：|
1、界面：执行前只勾选少量指标收集
2、api：正常会比界面快，但最快也是2-3秒

**Comment by rafa0128** [comment]
我试过内存16G的电脑所有指标一起收集，速度也是飞起，1-2秒收集一次，8G就开始有点慢了

**Comment by EnjoY1024** [comment]
> > 
> 
> 是一个指标2-3秒吗，同时跑多个试的是4s+

16G 3个指标4-5s api 怎么调整频率哇

**Comment by rafa0128** [comment]
> > > 
> > 
> > 
> > 是一个指标2-3秒吗，同时跑多个试的是4s+
> 
> 16G 3个指标4-5s api 怎么调整频率哇

可以优化但是空间不大了，你多个指标用api是怎么收集的？多线程还是多进程？

**Comment by rafa0128** [comment]
2.5.2已经把api收集优化了，我8G内存机器还是要2-3秒浮动，这个已经是最优了，计算也要花时间的。ios还会慢一些，pc和手机的通信更需要时间。只能用sleep调慢不能再快了。

**Comment by rafa0128** [comment]
2.5.2已经把api收集优化了，我8G内存机器还是要2-3秒浮动，这个已经是最优了，计算也要花时间的。ios还会慢一些，pc和手机的通信更需要时间。只能用sleep调慢不能再快了。
