### ISSUE TITLE
查看报告网页报错

### ISSUE THREAD

**Issue by jialeigd** [smart-test-ti/SoloX#123]
复现路径：iOS测试后点击停止，查看报告，报告中折线图为空
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/5088304/225853571-718bbf79-d6d0-447f-8d83-6f8765e83a25.png">
查看浏览器控制台有如下报错：
<img width="854" alt="image" src="https://user-images.githubusercontent.com/5088304/225853788-6906cb5b-7307-4420-936d-1005c034701d.png">
另外这里的平均值也一直没有：
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/5088304/225853910-827103d0-079d-48c8-99cb-c6de46375aa8.png">

**Comment by rafa0128** [comment]
看截图，你的包名是空的吗？估计保存数据失败了，看本地还有没有数据

**Comment by jialeigd** [comment]
> 看截图，你的包名是空的吗？估计保存数据失败了，看本地还有没有数据

包名应该不为空，测试过程中都有。您说的看本地还有没有数据怎么看？

**Comment by rafa0128** [comment]
报告页截图看看，还有你执行的当前路径应该有一个report文件夹，里面的数据打包传上来看看

**Comment by jialeigd** [comment]
> 报告页截图看看，还有你执行的当前路径应该有一个report文件夹，里面的数据打包传上来看看
报告页截图
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/5088304/225868727-4441b2c4-d848-4e06-b669-b43bcdbc231e.png">
报告如下，另外电量数据也没有采集上来
[apm_2023-03-17-17-40-26.zip](https://github.com/smart-test-ti/SoloX/files/10999904/apm_2023-03-17-17-40-26.zip)

**Comment by rafa0128** [comment]
那就是battery的漏写到log里了，上次你没发现这里吗，下周再修复吧，先好好过周末。
麻烦再看看ios battery监控过程中有没有数据哈，要是有问题一起提了，我现在没有ios设备了。

**Comment by jialeigd** [comment]
> 那就是battery的漏写到log里了，上次你没发现这里吗，下周再修复吧，先好好过周末。 麻烦再看看ios battery监控过程中有没有数据哈，要是有问题一起提了，我现在没有ios设备了。

周末愉快！battery数据采集过程中就没有，上次没太注意这里。

**Comment by jialeigd** [comment]
大神，更新了2.5.1版本，还有无法显示出报告折线图，chrome控制台页面报错一样，日志路径下也没有battery的日志
<img width="504" alt="image" src="https://user-images.githubusercontent.com/5088304/226232015-0329bbd3-f351-4fbf-b551-0843cce52d85.png">

**Comment by rafa0128** [comment]
> 大神，更新了2.5.1版本，还有无法显示出报告折线图，chrome控制台页面报错一样，日志路径下也没有battery的日志 <img alt="image" width="504" src="https://user-images.githubusercontent.com/5088304/226232015-0329bbd3-f351-4fbf-b551-0843cce52d85.png">

等10分钟再下载2.5.2，漏改了一点点东西

**Comment by rafa0128** [comment]
感觉上个版本也没有问题，确认下载的是2.5.1吗？

**Comment by jialeigd** [comment]
> 感觉上个版本也没有问题，确认下载的是2.5.1吗？

我看页面显示的是2.5.2版本了，但是运行时还是没有电量数据和日志，停止后无法生成报告折线图
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/5088304/226237587-8ff1681f-4442-4f72-a560-60e7440e5e5e.png">

**Comment by jialeigd** [comment]
我看通过接口获取电量日志没问题，是不是前端显示的问题？

**Comment by rafa0128** [comment]
/apm/battery，看下chrome的日志显示这个接口是不是报错了，信息给我看看

**Comment by jialeigd** [comment]
chrome似乎没有保存信息，但是我只开启电量和内存指标的话，控制台输出只有内存数据，网络也显示调用了/api/mem接口，没有/api/battery的调用
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/5088304/226239512-c620f2e0-50be-468b-ae6c-b5a5b1dcc621.png">
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/5088304/226239555-1d0ebb91-48ad-440d-910c-f465a05763a5.png">

**Comment by jialeigd** [comment]
大神有什么交流群吗，方便交流

**Comment by rafa0128** [comment]
![1679283063622](https://user-images.githubusercontent.com/24454096/226240718-14f9dcf3-60f2-48f3-bcda-7fedec301596.png)
找到问题了，快吐血了

**Comment by rafa0128** [comment]
> 大神有什么交流群吗，方便交流

现在没有了，不想维护这种群太累，里面交流七嘴八舌的，还不如留问题记录在github，其他人来了可以看一些历史问题的解释

**Comment by rafa0128** [comment]
> 大神有什么交流群吗，方便交流

现在没有了，不想维护这种群太累，里面交流七嘴八舌的，还不如留问题记录在github，其他人来了可以看一些历史问题的解释

**Comment by jialeigd** [comment]
> ![1679283063622](https://user-images.githubusercontent.com/24454096/226240718-14f9dcf3-60f2-48f3-bcda-7fedec301596.png) 找到问题了，快吐血了

原来如此

**Comment by jialeigd** [comment]
> > 大神有什么交流群吗，方便交流
> 
> 现在没有了，不想维护这种群太累，里面交流七嘴八舌的，还不如留问题记录在github，其他人来了可以看一些历史问题的解释

好的
