### ISSUE TITLE
Windows下路径读取失败，report export failed ，并且分析文件也没有具体内容

### ISSUE THREAD

**Issue by mnvum** [smart-test-ti/SoloX#125]
![image](https://user-images.githubusercontent.com/36786180/226855315-9388ec61-86ed-4a63-ac9b-9569fc42b174.png)

如图，Windows export report 的路径辛苦处理一下

**Comment by mnvum** [comment]
![image](https://user-images.githubusercontent.com/36786180/226855972-6bcb0885-b85e-4e41-8053-38cc89b8624f.png)

**Comment by rafa0128** [comment]
这里可能是你只勾选收集了个别指标，就会出现这种情况。报告分析只支持所有指标搜集的情况分析

**Comment by rafa0128** [comment]
低优先级吧，后面有时间兼容这种情况

**Comment by mnvum** [comment]
> 这里可能是你只勾选收集了个别指标，就会出现这种情况。报告分析只支持所有指标搜集的情况分析

好的谢谢，指标勾选全部之后，已正常
