### ISSUE TITLE
【体验】该程序无法设置采集的时间

### ISSUE THREAD

**Issue by haojunwei-hub** [smart-test-ti/SoloX#127]
性能场景：测试性能时一般都需要采集指定时间段内的数据，如果能设置采集时长就更好了；

**Comment by rafa0128** [comment]
> 性能场景：测试性能时一般都需要采集指定时间段内的数据，如果能设置采集时长就更好了；

超过采集时长就自动帮你保存吗？

**Comment by haojunwei-hub** [comment]
> > 性能场景：测试性能时一般都需要采集指定时间段内的数据，如果能设置采集时长就更好了；
> 
> 超过采集时长就自动帮你保存吗？

是的，超过设置采集时长，自动保存数据

**Comment by rafa0128** [comment]
这个可以，下个版本
