### ISSUE TITLE
iphone 手机是否支持无线模式连接？ 有线模式下，获取的耗电量值，没有参考的意义

### ISSUE THREAD

**Issue by haojunwei-hub** [smart-test-ti/SoloX#128]

**Comment by rafa0128** [comment]
是能量损耗，不是电量，和充不充电没关系

**Comment by haojunwei-hub** [comment]
> 是能量损耗，不是电量，和充不充电没关系

请教下大佬，这个能耗是怎么计算的，

**Comment by rafa0128** [comment]
你本地的xcode中instruments提供的数据

**Comment by rafa0128** [comment]
可以去看一下perfdog的文档说明各个指标怎么计算的

**Comment by haojunwei-hub** [comment]
> 可以去看一下perfdog的文档说明各个指标怎么计算的

嗯呢，提出这个疑问，主要也是之前用过perfdog ，perfdog也要求无线模式下测功耗，项目上也用过API获取过功耗，因为功耗跟电流有关系，USB模式下手机处于充电模式，会影响手机放电的电流，故提出此疑问；

**Comment by rafa0128** [comment]
计算肯定是和电流有关power = current * voltage / 1000
perfdog其实也是用instrument的数据的，至于是不是影响指标的大小我觉得不是特别关键，只要你的参照物的环境是一样就好，新旧版本或者竞品都是一样收集。
