### ISSUE TITLE
2.5.5版本运行报错

### ISSUE THREAD

**Issue by jialeigd** [smart-test-ti/SoloX#130]
2.5.4以上版本python3 -m solox 报错如下：
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/5088304/228196411-6cc5652b-7fa0-4f97-954f-d41a8e289e50.png">
安装2.5.3版本正常

**Comment by rafa0128** [comment]
升级你的python版本，注意看v2.5.5的说明
