### ISSUE TITLE
大佬，安卓端是否有计划支持监控GPU？

### ISSUE THREAD

**Issue by haojunwei-hub** [smart-test-ti/SoloX#135]
毕竟GPU也是性能一个重要指标，

**Comment by rafa0128** [comment]
后面有时间可以研究一下，最近停更2个月，你可以参考下perfdog的指标看下
https://perfdog.qq.com/article_detail?id=10161&issue_id=0&plat_id=1
https://perfdog.qq.com/article_detail?id=10221&issue_id=0&plat_id=1

**Comment by rafa0128** [comment]
基本做不了了，安卓现在权限收紧了，没有root的手机访问不了gpu的文件
