### ISSUE TITLE
Android的总是出现这样的报错，每当我要下载测试记录的时候

### ISSUE THREAD

**Issue by hnxaky** [smart-test-ti/SoloX#137]
![image](https://user-images.githubusercontent.com/107181681/229475190-fbfdcb55-a2ae-491e-b6fa-fe338130d56a.png)
![Uploading 2023-04-03_175126.png…]()

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/issues/125
相同问题
