### ISSUE TITLE
使用python收集可以调节获取频率吗？感觉好慢

### ISSUE THREAD

**Issue by 986379041** [smart-test-ti/SoloX#140]

**Comment by rafa0128** [comment]
多慢？不同指标的速度不一样的，如果是计算百分比的指标，一般都要2-3秒，因为要取间隔一秒两个值来计算，计算也得花1秒左右吧，有些指标不需要计算就特别快，还要取决你的电脑配置
![image](https://user-images.githubusercontent.com/24454096/231369056-eebf10f2-1c23-4b0c-a0b2-6ebd8c50551d.png)

**Comment by 986379041** [comment]
apm.py文件里的“time.sleep(1)”可以调整吗？这个如果去掉会有什么影响吗？但我感觉去掉之后的结果跟加上的结果差异比较大
