### ISSUE TITLE
安卓 app cpu占比 偶尔超过100%，是因为多核cpu吗？

### ISSUE THREAD

**Issue by superWenshuo** [smart-test-ti/SoloX#141]
机型 ：f0fc48fd
获取方式python 3.9+solox =2.5.3

**Comment by M2asXe** [comment]
+1，另外问一下安卓的app cpu是normalized吗

**Comment by rafa0128** [comment]
正常应该不会超过100%才对，但是已经用了top的计算方式了，具体怎么计算可以看
https://github.com/smart-test-ti/SoloX/blob/master/DocForAndroid.md

**Comment by superWenshuo** [comment]
> 正常应该不会超过100%才对，但是已经用了top的计算方式了，具体怎么计算可以看 https://github.com/smart-test-ti/SoloX/blob/master/DocForAndroid.md
看了下规则，猜测可能是因为我多次重启app，造成部分数据是0，做逻辑运算时错误。推荐怎么处理下？我目前是用appium+pytest 涉及多次app的关闭，我暂时判断了cpu数值大于100，小于0不计算。其余的数据写入数据库。多谢指导
