### ISSUE TITLE
在连接的时候，出现了host error，有没有优化方式 

### ISSUE THREAD

**Issue by hnxaky** [smart-test-ti/SoloX#144]
在连接的时候，出现了host error，有没有优化

**Comment by rafa0128** [comment]
是不是配置了agent
![image](https://user-images.githubusercontent.com/24454096/233940696-9f3cf94c-eac4-428a-a308-97d5b2455771.png)

**Comment by haojunwei-hub** [comment]
> 是不是配置了agent ![image](https://user-images.githubusercontent.com/24454096/233940696-9f3cf94c-eac4-428a-a308-97d5b2455771.png)

没有配置agent ，我也遇到了同样的问题

**Comment by hnxaky** [comment]
请求的rul就是本地地址localhost的地址




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafa ***@***.***&gt;; 
发送时间: 2023年4月24日(星期一) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smart-test-ti/SoloX] 在连接的时候，出现了host error，有没有优化方式  (Issue #144)





 
F12看下是什么报错，你们的host非法了，看看请求的url是什么
 
&mdash;

**Comment by rafa0128** [comment]
应该不会出现localhost的，如果你按照python -m solox启动的话

**Comment by hnxaky** [comment]
是的，显示的是我现在的内网的IP地址，而且是最新的这个版本，
还有个问题，就是我们在测试ios的时候，发现16.3以上的版本不兼容，
我这边出现host error之后，只能获取电池的数据，
我在同事的电脑中，用低于16.3版本ios系统，会报something error，同时也有部分数据无法获取，CPU。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafa ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 下午2:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smart-test-ti/SoloX] 在连接的时候，出现了host error，有没有优化方式  (Issue #144)





 
应该不会出现localhost的，如果你按照python -m solox启动的话
 
&mdash;

**Comment by rafa0128** [comment]
报错日志提供一下，终端应该都会有日志的

**Comment by hnxaky** [comment]
好，这两天我看一下发你吧，现在有点忙




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafa ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smart-test-ti/SoloX] 在连接的时候，出现了host error，有没有优化方式  (Issue #144)





 
报错日志提供一下，终端应该都会有日志的

**Comment by rafa0128** [comment]
以后有问题要提供详细信息：https://github.com/smart-test-ti/SoloX/issues/49，就一句话看的心累

**Comment by hnxaky** [comment]
好嘞，麻烦了，以后我会提供充足的信息和结论，以便问题分析




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafa ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 下午3:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [smart-test-ti/SoloX] 在连接的时候，出现了host error，有没有优化方式  (Issue #144)





 
以后有问题要提供详细信息：https://github.com/smart-test-ti/SoloX/issues/49，就一句话看的心累
