### ISSUE TITLE
选择应用名称后，提示：[W 230426 18:05:48 common:81] no pid found

### ISSUE THREAD

**Issue by ls1509** [smart-test-ti/SoloX#146]
由于common.py文件中 getPid()方法 shell ps -ef 中的-ef在windows系统中会导致获取不到进程信息，从而获取不到Pid，导致内存信息获取的时候报错

**Comment by ls1509** [comment]
![image](https://user-images.githubusercontent.com/20093481/234544261-2ca79fd7-1aca-4851-b819-77ddda483f34.png)

**Comment by rafa0128** [comment]
-ef是显示所有进程，不加的话有些进程windows是不展示的，你确定你的app进程还在吗？重新连接跑一下？不太可能有问题这里

**Comment by ls1509** [comment]
明白了；可能只是我电脑的环境有问题，因为我执行获取pid命令的时候会有错误返回
C:\Users\ls150>adb shell ps -ef
bad pid '-ef'
打扰了

**Comment by rafa0128** [comment]
后续按照规范提问题。https://github.com/smart-test-ti/SoloX/issues/49
