### ISSUE TITLE
python -m solox 打开的页面中的连接和开始无法使用。

### ISSUE THREAD

**Issue by loneyao** [smart-test-ti/SoloX#149]
python -m solox 打开的页面中的连接和开始无法使用。
选择了设备，和要采集的app，然后去点连接和开始，页面会刷新。
不去点连接和开始，页面采集的性能数据都是0

我要怎么页面上可以显示性能指标数据。

**Comment by rafa0128** [comment]
你能选择设备和app就代表你的设备连接上了，就不用去点connect了。直接点start就行

**Comment by loneyao** [comment]
> 你能选择设备和app就代表你的设备连接上了，就不用去点connect了。直接点start就行

如果app不能选择，会是什么问题。要怎么解决。

**Comment by rafa0128** [comment]
截图上来，不知道说刷
