### ISSUE TITLE
【QA】手动收集性能指标后，怎么生成html报告

### ISSUE THREAD

**Issue by loneyao** [smart-test-ti/SoloX#150]
from solox.public.apm import APM
from solox.public.common import Devices

d = Devices()
pids = d.getPid(deviceId='emulator-5554', pkgName='com.bilibili.app.in')

apm = APM(pkgName='com.bilibili.app.in',deviceId='emulator-5554',platform='Android',
          surfaceview=True)
cpu = apm.collectCpu()  # %
memory = apm.collectMemory()  # MB
flow = apm.collectFlow(wifi=True)  # KB
fps = apm.collectFps()  # HZ
battery = apm.collectBattery()  # level:% temperature:°C current:mA voltage:mV power:w

**Comment by rafa0128** [comment]
等2.6.1版本就会有，但下个版本会一段时间后才会发布，看心情和精力

**Comment by rafa0128** [comment]
2.6.1已经有这个功能
