### ISSUE TITLE
SoloX has stopped updating, and 2.6.2 is the last version.

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#157]
就SoloX目前的技术方案，基本做到头了，2.6.2是最后一个版本，不会继续更新，请需要二次开发的clone/forks代码到自己的仓库。新问题不再回复和解决。

**Comment by loneyao** [comment]
if __name__ == '__main__':
    while True:
        cmd = os.popen('adb -s %s shell "dumpsys window | grep mCurrentFocus"' % equipment)
        result = cmd.read()
        if packageName not in result:
            print('停止收集')
            break
        else:
            cpu = apm.collectCpu()  # % jank
            memory = apm.collectMemory()  # MB
            flow = apm.collectFlow(wifi=True)  # KB
            fps = apm.collectFps()  # HZ
            battery = apm.collectBattery()  # level:% temperature:°C current:mA voltage:mV power:w
            apm = APM(pkgName=packageName, platform='Android', deviceId=equipment,
                      surfaceview=True, noLog=False, pid=None, duration=300)  # duration : second

            print('生成报告')
            apm.collectAll()
我目前是用判断应用是不是处于前台，来终止循环，但是有个问题。采集这块，终止会有问题。

**Comment by rafa0128** [comment]
> if **name** == '**main**': while True: cmd = os.popen('adb -s %s shell "dumpsys window | grep mCurrentFocus"' % equipment) result = cmd.read() if packageName not in result: print('停止收集') break else: cpu = apm.collectCpu() # % jank memory = apm.collectMemory() # MB flow = apm.collectFlow(wifi=True) # KB fps = apm.collectFps() # HZ battery = apm.collectBattery() # level:% temperature:°C current:mA voltage:mV power:w apm = APM(pkgName=packageName, platform='Android', deviceId=equipment, surfaceview=True, noLog=False, pid=None, duration=300) # duration : second
> 
> ```
>         print('生成报告')
>         apm.collectAll()
> ```
> 
> 我目前是用判断应用是不是处于前台，来终止循环，但是有个问题。采集这块，终止会有问题。

靠自己了

**Comment by Nightwish555** [comment]
大佬接下来是考虑换技术方案，还是就暂时搁置了？

**Comment by rafa0128** [comment]
> 大佬接下来是考虑换技术方案，还是就暂时搁置了？

没精力做了，可能会修复bug，看bug情况
