### ISSUE TITLE
多设备同时接入，点击start提示错误

### ISSUE THREAD

**Issue by zoushibo123** [smart-test-ti/SoloX#16]
![image](https://user-images.githubusercontent.com/102923181/165029930-86aef3fe-02bc-4c52-a836-710df4c37a0f.png)

![image](https://user-images.githubusercontent.com/102923181/165029882-287e801f-2a92-43a8-be2d-9ff109365a3f.png)

**Comment by rafa0128** [comment]
> ![image](https://user-images.githubusercontent.com/102923181/165029930-86aef3fe-02bc-4c52-a836-710df4c37a0f.png)
> 
> ![image](https://user-images.githubusercontent.com/102923181/165029882-287e801f-2a92-43a8-be2d-9ff109365a3f.png)

fixed

**Comment by zoushibo123** [comment]
> 
> 固定的

还是不行，报同样的错

**Comment by zoushibo123** [comment]
> 
> fixed
还是不行，报同样的错

**Comment by rafa0128** [comment]
> 

查看版本是否是1.0.36，自测是没有问题了的

**Comment by zoushibo123** [comment]
> > 
> 
> 查看版本是否是1.0.36，自测是没有问题了的

不好意思光clone了，没执行pip3 install -U solox，执行完升到1.0.36就好了，抱歉
