### ISSUE TITLE
Save IOS data will stuck and not saving.

### ISSUE THREAD

**Issue by hansyuanyang** [smart-test-ti/SoloX#164]
After capture ios data, if I hit save buttin, Save data window will pop-up and state "Saving data to generate report, please do not leave." However it takes forever and not really saving anything. But in Andorid's capture is fine.  Is there anyways to fix it? Thank you.

**Comment by rafa0128** [comment]
please show me the error log

**Comment by hansyuanyang** [comment]
`[I 230529 16:03:34 common:183] Clean up useless files ...
[I 230529 16:03:34 common:184] Hi there ...
[I 230529 16:03:34 common:190] Clean up useless files success
192.168.26.12 - - [29/May/2023 16:03:34] "POST /apm/initialize HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:36] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401140 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:37] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401139 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:37] "GET /apm/gpu?pkgname=com.nexon.hit2tw&_=1685347401141 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:38] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401138 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:38] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401142 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:39] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401137 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:39] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401145 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:39] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401143 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:40] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401147 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:41] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401144 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:41] "GET /apm/cpu?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401136 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:42] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401149 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:42] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401148 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:43] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401151 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:43] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401146 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:44] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401153 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:44] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401152 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:44] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401150 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:45] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401155 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:46] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401158 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:46] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401156 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:47] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401159 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:48] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401157 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:48] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401154 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:49] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401161 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:49] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401160 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:50] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401164 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:51] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401166 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:51] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401162 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:51] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401165 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:52] "POST /socket.io/?EIO=3&transport=polling&t=1685347432190-7&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:52] "GET /socket.io/?EIO=3&transport=polling&t=1685347406197-6&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:52] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401167 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:52] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401163 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:53] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401170 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:54] "GET /apm/fps?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&surv=false&_=1685347401169 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:54] "GET /apm/create/report?platform=iOS&model=normal&app=com.nexon.hit2tw&devices=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&_=1685347401173 HTTP/1.1" 400 -
192.168.26.12 - - [29/May/2023 16:03:54] "GET /apm/network?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&process=&_=1685347401168 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:54] "GET /apm/battery?platform=iOS&device=iPhone12PM%3A00008101-00154CD03E69001E&_=1685347401172 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:03:57] "GET /apm/mem?model=normal&platform=iOS&pkgname=com.nexon.hit2tw&device=iPhone12PM%3A00008101-00154CD03E69001E&process=&_=1685347401171 HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:04:18] "POST /socket.io/?EIO=3&transport=polling&t=1685347458196-9&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:04:18] "GET /socket.io/?EIO=3&transport=polling&t=1685347432196-8&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:04:44] "POST /socket.io/?EIO=3&transport=polling&t=1685347484199-11&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -
192.168.26.12 - - [29/May/2023 16:04:44] "GET /socket.io/?EIO=3&transport=polling&t=1685347458204-10&sid=aa45b3bd27e74b7fa74b9b846298321f HTTP/1.1" 200 -`

When I hit "save", I think mainly happened this log: "GET /apm/create/report?platform=iOS&model=normal&app=com.nexon.hit2tw&devices=iPhone12PM%3A00008101-00154CD03E69001E&wifi_switch=false&_=1685347401173 HTTP/1.1" 400 -

Thank you.
