### ISSUE TITLE
not getting fps values

### ISSUE THREAD

**Issue by itsMyRepos** [smart-test-ti/SoloX#167]
getting this below error,

[E 230530 12:16:16 fps:265] an exception hanpend in fps _collector_thread , reason unkown!
[D 230530 12:16:16 fps:267] Traceback (most recent call last):
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 240, in _collector_thread
        refresh_period, new_timestamps = self._get_surfaceflinger_frame_data()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 378, in _get_surfaceflinger_frame_data
        self.focus_window = self.get_surfaceview_activity()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\solox\public\fps.py", line 70, in get_surfaceview_activity
        activity_name = activity_line.split(' ')[2]
                        ~~~~~~~~~~~~~~~~~~~~~~~~^^^
    IndexError: list index out of range

**Comment by rafa0128** [comment]
please run "adb shell dumpsys SurfaceFlinger --list | grep [packagname]", and show me the result

**Comment by itsMyRepos** [comment]
this is the output of the command, i am checking for subwaysurfer
3b40aef ActivityRecordInputSink com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36981
ActivityRecord{1405bce u0 com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity}#36973
f82a80f com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36982
Background for SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity]#36989
SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity]#36987
SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity](BLAST)#36988
com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36983
Bounds for - com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36986

**Comment by pawanindium** [comment]
please help to check this, thanks

**Comment by rafa0128** [comment]
> please help to check this, thanks

Will be fixed in the next version

**Comment by rafa0128** [comment]
> this is the output of the command, i am checking for subwaysurfer
> 
> 3b40aef ActivityRecordInputSink com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36981 ActivityRecord{1405bce u0 com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity}#36973 f82a80f com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36982 Background for SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity]#36989 SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity]#36987 SurfaceView[com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity](BLAST)#36988 com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36983 Bounds for - com.kiloo.subwaysurf/com.sybogames.chili.multidex.ChiliMultidexSupportActivity#36986

Step1 :  You can turn off the 'SurfaceView' switch
Step2 : Set the following settings on your phone： (Developer - GPU rendering mode - adb shell dumpsys gfxinfo)
