### ISSUE TITLE
为什么通过Python获取的结果跟网页平台获取的结果差异很大？

### ISSUE THREAD

**Issue by 986379041** [smart-test-ti/SoloX#168]
Python代码获取：memory: {'totalPass': 23.28, 'nativePass': 1.03, 'dalvikPass': 1.69}
![image](https://github.com/smart-test-ti/SoloX/assets/52530860/5c43ccfb-8162-479c-a62b-bf8f9ffed337)
平台获取：600+、100+、10+
![image](https://github.com/smart-test-ti/SoloX/assets/52530860/5f97094f-d206-49aa-8e59-3d08b9669b84)

**Comment by rafa0128** [comment]
调同一个方法的，确认对比的场景一不一样
