### ISSUE TITLE
Getting this error for  a new system

### ISSUE THREAD

**Issue by RYG81** [smart-test-ti/SoloX#173]
![issue](https://github.com/smart-test-ti/SoloX/assets/10570236/efb37ccd-bdb8-4ba2-b9ed-9ac5ccf170bb)
On my new system I am getting this error. Don't know why.
please help

**Comment by rafa0128** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/24454096/6f36e09b-051d-44ac-9752-c3a45ffe5e86)

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/issues/114
