### ISSUE TITLE
获取不到内存信息，刚刚下载的项目，本机python环境3.10.6版本

### ISSUE THREAD

**Issue by Ticooooooo** [smart-test-ti/SoloX#176]
![image](https://github.com/smart-test-ti/SoloX/assets/138653213/bb6e01c1-e74c-424c-9d0c-886b70faf368)
![image](https://github.com/smart-test-ti/SoloX/assets/138653213/dd537a96-c143-4cd7-9cd8-5ecd16dcf787)

**Comment by Ticooooooo** [comment]
其他的数据可以正常获取，大佬看下这个问题，是我这边儿配置的问题吗

**Comment by rafa0128** [comment]
重新连接也是那样吗？自己敲一下adb shell dumpsys meminfo {pid}看看结果

**Comment by TicoGuo** [comment]
更新到最新版看了下， 已经修复了此问题

**Comment by TicoGuo** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/124109942/26a74790-441d-41ee-b1c3-3947cbd45496)
![image](https://github.com/smart-test-ti/SoloX/assets/124109942/1d4201ff-a390-4d81-b273-54d337c759b7)
刚才首次启动可以获取内存信息，现在又获取不到了，信息如下

**Comment by rafa0128** [comment]
确定进程还在吗？出现这种情况就是进程不在了

**Comment by TicoGuo** [comment]
是我的使用方法不对，需要先开启对应app 获取进程后再检测即可
