### ISSUE TITLE
ios 12.5.7 无法使用性能获取：因为cmd执行tidevice获取的数据无法decode

### ISSUE THREAD

**Issue by 1033866383** [smart-test-ti/SoloX#178]
![image](https://github.com/smart-test-ti/SoloX/assets/56209295/10e66e03-a6b7-49c5-abff-0ddba4783c08)
这里因为第一次使用会报错，我修改了一部分代码测试了下：
1.打印了返回值
2.使用默认的decode，因为我怕我的编码设置有问题，但是看起来我的默认也是utf-8
![image](https://github.com/smart-test-ti/SoloX/assets/56209295/cbc564ef-cdfb-4324-b390-913f98bd2b4f)

我是：https://github.com/1033866383/perf-orange-cat  的作者，希望也可以看看我的项目，我的ios性能获取是直接使用tidevice的api，这样可能更简单稳定一些
![image](https://github.com/smart-test-ti/SoloX/assets/56209295/87ffa57b-0b37-4796-ac99-8bfef7965b4f)

**Comment by rafa0128** [comment]
重复弄没太大意义，收集方法大同小异，没法推进工具的进步。目前要把指标优化精确不能只用adb和tidevice的方式了（fps\流量严格来说是不够准确的），得有个像perfdog一样监听app装在手机上，要用原生的api收集。我建议往移动端收集研究，这样肯定会很火的。如果有兴趣和能够往移动端开发优化收集的话，可以让你来维护SoloX，目前这边正在找后续的开发人员。

**Comment by 1033866383** [comment]
> 重复弄没太大意义，收集方法大同小异，没法推进工具的进步。目前要把指标优化精确不能只用adb和tidevice的方式了（fps\流量严格来说是不够准确的），得有个像perfdog一样监听app装在手机上，要用原生的api收集。我建议往移动端收集研究，这样肯定会很火的。如果有兴趣和能够往移动端开发优化收集的话，可以让你来维护SoloX，目前这边正在找后续的开发人员。

收到，但是现在 12.5.7的ios使用会卡在一开始获取包的时候。辛苦看下问题吧

**Comment by 1033866383** [comment]
> 重复弄没太大意义，收集方法大同小异，没法推进工具的进步。目前要把指标优化精确不能只用adb和tidevice的方式了（fps\流量严格来说是不够准确的），得有个像perfdog一样监听app装在手机上，要用原生的api收集。我建议往移动端收集研究，这样肯定会很火的。如果有兴趣和能够往移动端开发优化收集的话，可以让你来维护SoloX，目前这边正在找后续的开发人员。

感谢指路，后面我看看做adb sdk 嵌入性能获取，看看能不能更准确
