### ISSUE TITLE
【bug】win电脑+ios手机，使用python获取app的状态信息时，创建apm对象时json解析出错

### ISSUE THREAD

**Issue by Sgr-Ice** [smart-test-ti/SoloX#181]
![image](https://github.com/smart-test-ti/SoloX/assets/89150750/530842d5-d027-433a-88a7-75edc8f8da05)

我这边获取的设备信息如下：
'[
    {
        "udid": "00008110-000C49C122C0401E",
        "serial": "TL71F2F7KP",
        "name": "123",
        "market_name": "iPhone 13 Pro Max",
        "product_version": "16.0",
        "conn_type": "usb"
    }
]
\x1b[0m'

应该是common.py 里的106 行，解析上面的json报错。
麻烦大佬看看~

**Comment by rafa0128** [comment]
截图具体提示的报错看看，这个之前解决了但是没有机器测试

**Comment by Sgr-Ice** [comment]
> 截图具体提示的报错看看，这个之前解决了但是没有机器测试

![image](https://github.com/smart-test-ti/SoloX/assets/89150750/391db1f0-c51e-4e70-afc5-084843539a24)
这个可以吗
