### ISSUE TITLE
【win电脑+ios手机】网络接收数据那块的数据，看起来算错了

### ISSUE THREAD

**Issue by Sgr-Ice** [smart-test-ti/SoloX#182]
![image](https://github.com/smart-test-ti/SoloX/assets/89150750/ed4aa0e8-eefd-4bde-aedf-c929863d52a5)

![image](https://github.com/smart-test-ti/SoloX/assets/89150750/1b251354-8463-426d-96a8-ad2d34d4af79)

这个数值，应该是重复相加了。
最终的recv数据应该是最后那个绿色波峰7027.11kb吧
麻烦大佬看看，

**Comment by rafa0128** [comment]
就是统计你这段时间总的流量损耗

**Comment by Sgr-Ice** [comment]
> 就是统计你这段时间总的流量损耗

我的意思是，看起来现在每个统计周期内的流量是累加的。
比如，如果是1s统计一次流量消耗，

app实际的收到的流量如下：
第一秒：recv 1MB
第二秒：recv 1MB
第三秒：recv 1MB
3s共计 接收到流量= 3MB

目前统计到的流量如下：
第一秒：recv 1MB
第二秒：recv 2MB
第三秒：recv 3MB
3s共计 接收到流量： 1+2+3 = 6MB

**Comment by rafa0128** [comment]
看你的chart线就不是你说的情况，如果每秒都是累加就不会出现起伏
