### ISSUE TITLE
record android device screen

### ISSUE THREAD

**Issue by RYG81** [smart-test-ti/SoloX#184]
Hi,
Can we add functionality where we can have check box for recording device screen?
I searched little bit and found this library https://pypi.org/project/scrcpy-client/

but I am not that good at python. can this be done?
thanks in advance

**Comment by rafa0128** [comment]
being planned

**Comment by RYG81** [comment]
thanks for adding it so quick.

**Comment by RYG81** [comment]
Where to find recorded video?
