### ISSUE TITLE
安卓8以下的设备，好像不支持ps -ef，改成下边的这样就正常了

### ISSUE THREAD

**Issue by gradient30** [smart-test-ti/SoloX#187]
RT，改成下边的这样就正常了
if int(sdk_level) < 26:
	result = os.popen(f"{self.adb} -s {deviceId} shell ps | {self.filterType()} {pkgName}").readlines()
	获取进程时split需要多一位
	processList = ['{}:{}'.format(process.split()[1], process.split()[8]) for process in [result]]

**Comment by rafa0128** [comment]
你进入adb shell ，敲ps -ef发我看看

**Comment by gradient30** [comment]
> 你进入adb shell ，敲ps -ef发我看看

![image](https://github.com/smart-test-ti/SoloX/assets/39947529/a6cc6ed5-1708-4483-8840-2b9f7ca3faa3)
