### ISSUE TITLE
FPS统计无数据

### ISSUE THREAD

**Issue by milu534334864** [smart-test-ti/SoloX#19]
![image](https://user-images.githubusercontent.com/99703675/172314051-855c99f4-7d8b-472f-9b7b-ce7bf1cb1763.png)

**Comment by Pactortester** [comment]
1. 重新运行下看看能否生成，如果不行
2. 请把本地的log传上来，看下

**Comment by milu534334864** [comment]
是adblog吗
[2022061316_adb.log](https://github.com/smart-test-ti/SoloX/files/8889612/2022061316_adb.log)

**Comment by rafa0128** [comment]
> 是adblog吗 [2022061316_adb.log](https://github.com/smart-test-ti/SoloX/files/8889612/2022061316_adb.log)

这个是adb的日志文件，你好，请更新新版本看看还有没有这个问题哈，还有你是什么场景，如果是静态页面fps一般是为0才对的

**Comment by rafa0128** [comment]
如果解决了你的问题就star一下哈
