### ISSUE TITLE
Android抓取Battery時，數值不會變化

### ISSUE THREAD

**Issue by yanghansyuan** [smart-test-ti/SoloX#192]
以電池溫度為例，剛接上時會有數值(比如25度)，但之後就不會再變化了。除非再重新抓取一次，就會看到一開始的數值已經變成30度了，但再放著仍然溫度數值會保持不變。Iphone的話就會看到溫度一直升高的變化。麻煩大大幫忙看看

`[I 230802 14:10:05 common:61] Connected devices: ['19281FDEE000ZY(Pixel 6 Pro)']
192.168.26.12 - - [02/Aug/2023 14:10:06] "GET /device/ids?platform=Android&_=1690956597683 HTTP/1.1" 200 -
[W 230802 14:10:10 common:81] no pid found
192.168.26.12 - - [02/Aug/2023 14:10:10] "GET /package/pids?platform=Android&device=19281FDEE000ZY(Pixel%206%20Pro)&pkgname=com.nexon.dwm&_=1690956597684 HTTP/1.1" 200 -
[I 230802 14:10:17 common:183] Clean up useless files ...
[I 230802 14:10:17 common:189] Clean up useless files success
192.168.26.12 - - [02/Aug/2023 14:10:17] "POST /apm/initialize HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:17] "GET /apm/set/network?platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&wifi_switch=true&type=pre&process=&_=1690956597685 HTTP/1.1" 200 -
[E 230802 14:10:18 fps:74] get activity name failed, Please provide SurfaceFlinger --list information to the author
[I 230802 14:10:18 fps:75] dumpsys SurfaceFlinger --list info:
192.168.26.12 - - [02/Aug/2023 14:10:19] "GET /apm/network?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&wifi_switch=true&process=&_=1690956597688 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:19] "GET /apm/cpu?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&process=&_=1690956597686 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:20] "GET /socket.io/?EIO=3&transport=polling&t=1690956607153-4776&sid=0f834451317849d59b1a131c8dd41463 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:20] "GET /socket.io/?EIO=3&transport=polling&t=1690956606723-6&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:20] "GET /apm/fps?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&surv=true&_=1690956597689 HTTP/1.1" 200 -
[E 230802 14:10:20 apis:237] get memory data failed
Traceback (most recent call last):
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\view\apis.py", line 234, in getMEM
    totalPass, nativePass, dalvikPass = mem.getProcessMem()
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\public\apm.py", line 142, in getProcessMem
    totalPass, nativePass, dalvikPass = self.getAndroidMem() if self.platform == Platform.Android else self.getiOSMem()
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\public\apm.py", line 127, in getAndroidMem
    totalPass = round(float(float(m_total.group(1))) / 1024, 2)
AttributeError: 'NoneType' object has no attribute 'group'
192.168.26.12 - - [02/Aug/2023 14:10:20] "GET /apm/mem?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&process=&_=1690956597687 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:20] "GET /apm/battery?platform=Android&device=19281FDEE000ZY(Pixel%206%20Pro)&_=1690956597690 HTTP/1.1" 200 -
[E 230802 14:10:21 fps:74] get activity name failed, Please provide SurfaceFlinger --list information to the author
[I 230802 14:10:21 fps:75] dumpsys SurfaceFlinger --list info:
192.168.26.12 - - [02/Aug/2023 14:10:21] "GET /socket.io/?EIO=3&transport=polling&t=1690956620202-4777&sid=0f834451317849d59b1a131c8dd41463 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:21] "GET /socket.io/?EIO=3&transport=polling&t=1690956620205-7&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:21] "GET /apm/network?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&wifi_switch=true&process=&_=1690956597691 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:22] "GET /apm/cpu?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&process=&_=1690956597692 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:22] "GET /apm/battery?platform=Android&device=19281FDEE000ZY(Pixel%206%20Pro)&_=1690956597695 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:22] "GET /apm/fps?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&surv=true&_=1690956597693 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:23] "GET /socket.io/?EIO=3&transport=polling&t=1690956621208-4778&sid=0f834451317849d59b1a131c8dd41463 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:23] "GET /socket.io/?EIO=3&transport=polling&t=1690956621210-8&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:23] "POST /socket.io/?EIO=3&transport=polling&t=1690956623032-9&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
[E 230802 14:10:23 apis:237] get memory data failed
Traceback (most recent call last):
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\view\apis.py", line 234, in getMEM
    totalPass, nativePass, dalvikPass = mem.getProcessMem()
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\public\apm.py", line 142, in getProcessMem
    totalPass, nativePass, dalvikPass = self.getAndroidMem() if self.platform == Platform.Android else self.getiOSMem()
  File "E:\MyWorkFolder\DWM\Profiling\SoloX\SoloX_evn01\lib\site-packages\solox\public\apm.py", line 127, in getAndroidMem
    totalPass = round(float(float(m_total.group(1))) / 1024, 2)
AttributeError: 'NoneType' object has no attribute 'group'
192.168.26.12 - - [02/Aug/2023 14:10:23] "GET /apm/mem?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&process=&_=1690956597694 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:23] "GET /socket.io/?EIO=3&transport=polling&t=1690956623235-10&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
[E 230802 14:10:23 fps:74] get activity name failed, Please provide SurfaceFlinger --list information to the author
[I 230802 14:10:23 fps:75] dumpsys SurfaceFlinger --list info:
192.168.26.12 - - [02/Aug/2023 14:10:23] "GET /apm/network?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&wifi_switch=true&process=&_=1690956597696 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:24] "GET /socket.io/?EIO=3&transport=polling&t=1690956623229-4779&sid=0f834451317849d59b1a131c8dd41463 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:24] "GET /socket.io/?EIO=3&transport=polling&t=1690956623374-11&sid=0c091cd2b44d4486853a0e7ca4680c05 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:24] "GET /apm/battery?platform=Android&device=19281FDEE000ZY(Pixel%206%20Pro)&_=1690956597698 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:24] "GET /apm/cpu?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&process=&_=1690956597697 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:25] "GET /apm/fps?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&surv=true&_=1690956597699 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:25] "GET /apm/network?model=normal&platform=Android&pkgname=com.nexon.dwm&device=19281FDEE000ZY(Pixel%206%20Pro)&wifi_switch=true&process=&_=1690956597701 HTTP/1.1" 200 -
192.168.26.12 - - [02/Aug/2023 14:10:26] "GET /apm/battery?platform=Android&device=19281FDEE000ZY(Pixel%206%20Pro)&_=1690956597702 HTTP/1.1" 200 -
[E 230802 14:10:26 fps:74] get activity name failed, Please provide SurfaceFlinger --list information to the author
[I 230802 14:10:26 fps:75] dumpsys SurfaceFlinger --list info:
[E 230802 14:10:26 apis:237] get memory data failed`

**Comment by rafa0128** [comment]
这些错误日志和你说的问题无关，是因为你没有选择对应的app进程，或者app进程死掉了。电池温度的问题我看看。

**Comment by yanghansyuan** [comment]
謝謝大佬
