### ISSUE TITLE
内存的值一直没有变化

### ISSUE THREAD

**Issue by Rantigen** [smart-test-ti/SoloX#194]
![图片](https://github.com/smart-test-ti/SoloX/assets/94507032/fff9d53c-d656-41ba-9c11-e33a0c077219)
内存的值一直没有变化有没有人遇到过，需要怎么处理

**Comment by rafa0128** [comment]
看有没有什么异常日志，提供日志才能定位问题

**Comment by Sylviahh** [comment]
我也遇到这个问题：
手机设备是Redmi K40（Android11），网页版触发start后，无法获取到memory信息。
![log](https://github.com/smart-test-ti/SoloX/assets/25626251/a37c0492-e26a-497f-bd02-c9a1206c730b)
执行adb命令“adb -s 2bd3741c shell dumpsys meminfo 12438“，返回的信息里面，“TOTAL”后面不带冒号，导致正则不到数据，需要兼容下：
![adb](https://github.com/smart-test-ti/SoloX/assets/25626251/8ad2dfa8-d1a7-4656-9973-a751cb53c84f)

**Comment by rafa0128** [comment]
解了，等下个版本

**Comment by Fengqiaoyepo** [comment]
我这内存也是0，设备型号：oneplus5T(Android 10)
![image](https://github.com/smart-test-ti/SoloX/assets/54941134/c0ca945f-0f2e-4ad5-a599-d391b9185a6b)
执行dumpsys meminfo返回的信息界面
![image](https://github.com/smart-test-ti/SoloX/assets/54941134/30463bd4-bac3-4247-ba61-33f5833a542f)

**Comment by Fengqiaoyepo** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/54941134/2103bff4-a606-4e7f-9d39-23c85bed4a21)
![image](https://github.com/smart-test-ti/SoloX/assets/54941134/640594f3-58ac-4519-bad1-416c12ca8481)
回复上面的问题，我的设备用命令打印的swap关键字是：TOTAL SWAP (KB):
apm.py里的正则表达式有点问题，按照上面改下就行。
