### ISSUE TITLE
连接不上雷电模拟器

### ISSUE THREAD

**Issue by Ranshaoer** [smart-test-ti/SoloX#196]
每次都需要把 common.py 中的result['wifiadr'] = adb.shell(cmd=cmd, deviceId=deviceId).split(' ')[1]
修改成
_a= adb.shell(cmd=cmd, deviceId=deviceId).split(' ')
                result['wifiadr'] = _a[1] if len(_a) > 1 else ""
才能连接上模拟器，麻烦作者看看这里怎么帮处理下 要不然每次更新完都得修改下

**Comment by rafa0128** [comment]
> 每次都需要把 common.py 中的result['wifiadr'] = adb.shell(cmd=cmd, deviceId=deviceId).split(' ')[1] 修改成 _a= adb.shell(cmd=cmd, deviceId=deviceId).split(' ') result['wifiadr'] = _a[1] if len(_a) > 1 else "" 才能连接上模拟器，麻烦作者看看这里怎么帮处理下 要不然每次更新完都得修改下

看上去这种模拟器不支持获取wifi地址，我屏蔽掉就好
