### ISSUE TITLE
ios设备报 No process found, please start the app first.

### ISSUE THREAD

**Issue by Yuyuyang** [smart-test-ti/SoloX#197]
win11系统，可以正常识别设备，但是无法识别打开的app，请问可能是哪里的问题？
![图片](https://github.com/smart-test-ti/SoloX/assets/25746471/1db5b770-e1c6-419d-91ac-1d5edaf6a1de)

**Comment by rafa0128** [comment]
> win11系统，可以正常识别设备，但是无法识别打开的app，请问可能是哪里的问题？ ![图片](https://user-images.githubusercontent.com/25746471/259682954-1db5b770-e1c6-419d-91ac-1d5edaf6a1de.png)

只是提示有问题，这个是安卓的功能，不影响ios收集，下个版本改
