### ISSUE TITLE
设备链接不上

### ISSUE THREAD

**Issue by 420459906** [smart-test-ti/SoloX#202]
![image](https://github.com/smart-test-ti/SoloX/assets/142207472/c682878c-ffbc-49eb-96aa-9051911e770a)
![image](https://github.com/smart-test-ti/SoloX/assets/142207472/3f147396-f1e5-4c13-b3b7-b2b3389f8470)
设备链接不了呢

**Comment by rafa0128** [comment]
用过adb吗？不熟悉的话可以百度一下

**Comment by 420459906** [comment]
adb熟悉一点点，我是才入行的小白，我这是哪有问题的，麻烦大佬指点一下

**Comment by rafa0128** [comment]
你的手机看看开发者-允许调试开关看看有没有打开

**Comment by 420459906** [comment]
我开了的，刚刚才发现是我的这台手机usb授权有问题，刚刚换了一台手机就好了，谢谢大佬~~~

**Comment by rafa0128** [comment]
> 我开了的，刚刚才发现是我的这台手机usb授权有问题，刚刚换了一台手机就好了，谢谢大佬~~~

不客气，好用就帮忙点个star
