### ISSUE TITLE
有部分的package name找不到

### ISSUE THREAD

**Issue by marrash** [smart-test-ti/SoloX#203]
使用Rdemi 10 想確認如果開啟youtube時的效能  但找不到 com.google.android.youtube，也找不到任何跟youtube相關的pkg name

**Comment by rafa0128** [comment]
> com.google

之前我嫌弃谷歌自带的包名太多了，屏蔽了com.google开头的包名，你是用海外原生系统的手机吗？

**Comment by marrash** [comment]
對的，我是用海外原生系統的手機
