### ISSUE TITLE
iOS 设备无法连接

### ISSUE THREAD

**Issue by zackaryhuang** [smart-test-ti/SoloX#204]
```bash
"GET /static/logo/logo.png HTTP/1.1" 304 -
[E 230821 17:54:47 apis:88] 'gbk' codec can't decode byte 0xad in position 143: illegal multibyte sequence
```

看报错似乎与编码有关

```bash
 Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/view/apis.py", line 76, in deviceids
        pkgnames = d.getPkgnameByiOS(deviceinfos[0].split(':')[1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/public/common.py", line 130, in getPkgnameByiOS
        pkgResult = self.execCmd(f'tidevice --udid {udid} applist').split('\n')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/solox/public/common.py", line 36, in execCmd
        text = r.buffer.read().decode(encoding='gbk').replace('\x1b[0m','').strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 143: illegal multibyte sequence
```

```bash
tidevice list --json
```
```json
[
    {
        "udid": "00008110-0008696E34E3801E",
        "serial": "XXXXXXX",
        "name": "Zackary",
        "market_name": "iPhone 13",
        "product_version": "16.6",
        "conn_type": "usb"
    }
]
```

**Comment by rafa0128** [comment]
更新2.7.2版本

**Comment by zackaryhuang** [comment]
大佬更新太迅速了![image](https://github.com/smart-test-ti/SoloX/assets/31388697/e8cce83c-7bb2-4301-8447-c3367650fc56)
但是我这现在选不了 package 啊

**Comment by rafa0128** [comment]
> 大佬更新太迅速了![image](https://user-images.githubusercontent.com/31388697/261994358-e8cce83c-7bb2-4301-8447-c3367650fc56.png) 但是我这现在选不了 package 啊

有报错日志吗？

**Comment by rafa0128** [comment]
下载2.7.2版本应该不会有这个问题，你确定你下载对吗

**Comment by zackaryhuang** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/31388697/dc69a769-bc5e-4e8b-95c1-a9d1e0f06e2c)
 没有报错，版本也没问题，我 Android 的同事说他那也没有 package 列表

**Comment by rafa0128** [comment]
这么奇怪，有什么报错日志吗？



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Zackary ***@***.***> |
| 日期 | 2023年08月21日 18:51 |
| 收件人 | ***@***.***> |
| 抄送至 | Rafa ***@***.***>***@***.***> |
| 主题 | Re: [smart-test-ti/SoloX] iOS 设备无法连接 (Issue #204) |


没有报错，版本也没问题，我 Android 的同事说他那也没有 package 列表

**Comment by rafa0128** [comment]
实在没看出问题，执行tidevice --udid {udid} applist，看看有没有结果，udid 用你的设备。如果有结果然后浏览器F12看看打印的日志接口有没有返回

**Comment by zackaryhuang** [comment]
tidevice 命令是有结果的，但是 console 里打印的的是个空数组

![image](https://github.com/smart-test-ti/SoloX/assets/31388697/11b9b3a0-6d9e-4fc8-8627-89fc7866d02e)

**Comment by rafa0128** [comment]
给一下tidevice --udid {udid} applist结果我看看

**Comment by rafa0128** [comment]
> ```shell
>  tidevice --udid 00008110-0008696E34E3801E applist
> com.xgimi.XAssistant 极米 4.10.7
> com.sf-express.waybillcn 顺丰速运 9.55.1
> com.amazon.firetv.remote Fire TV 2.6.2
> com.airchina.CAMobile 中国国航 7.16.1
> com.taou.NeiTui 脉脉 6.3.6
> com.mmbang.neighborhood 叮咚买菜 11.0.1
> com.alipay.iphoneclient 支付宝 10.5.10
> com.freelancer.messenger Freelancer 4.10.0
> net.qihoo.360smartcamera 360摄像机 7.9.7
> com.growing.topwidgetsplus Top Widgets⁺ 1.6.0
> com.znxh.clean 拦截100 4.2.5
> com.taobao.movie.MoviePhoneClient 淘票票 11.0.6
> com.jingdong.jxj 京粉 3.12.46
> 95526.mobi 北京银行 7.0.7
> com.ishansong.shansong 闪送 6.4.50
> com.doglobal.ESFileExplorer ES文件浏览器 2.4.6
> com.cmbchina.cmblife 掌上生活 9.0.10
> com.smzdm.client.ios 什么值得买 10.5.7
> com.campmobile.snowcamera B612咔叽 12.2.16
> com.netease.cloudmusic 网易云音乐 8.10.51
> cn.gov.pbc.ecny 数字人民币 1.0.23
> thatisawesome.TestRAC TestRAC 1.0
> jp.co.sony.songpal.mdr Headphones 10.1.0
> com.atebits.Tweetie2 X 10.2
> cn.lanehub.talent 圆领超级个体 4.47.52
> com.xunlei.mvideo 迅雷 2.0.20
> com.icbc.iphoneclient 中国工商银行 1.8.75
> com.tencent.mqq QQ 8.9.75
> com.tencent.smoba 王者荣耀 8.4.10602
> notion.id Notion 0.4.1014
> com.nowcoder.app.florida 牛客 3.1.08
> com.burbn.instagram Instagram 296.0
> pinterest Pinterest 11.29.1
> com.jd.paidaojia1 京东到家 8.35.0
> com.tencent.wetype 微信输入法 1.1.3
> top.jwapp.zap ZAP短信 1.0.25
> spdbccc.com.cn 浦大喜奔 7.3.8
> com.homerun.petsmart 霍曼宠物 1.5.7
> com.xiaomi.youpin 小米有品 5.16.0
> com.xueqiu 雪球 14.23
> com.jkpang.PPHub PPHub 2.7.11
> CtClient 中国电信 10.4.1
> com.szzc.szzc 神州租车 8.0.9
> com.particlenews.newsbreak NewsBreak 23.33.0
> com.udemy Udemy 8.49.0
> com.chinaunicom.mobilebusiness 中国联通 10.7
> com.tmri.12123 交管12123 2.9.8
> com.auramarker.varlens Varlens 5.2.3
> com.jiangjia.gif 快手 11.6.20
> com.johnil.vvebo VVebo 3.3.31
> com.ss.iphone.ugc.Aweme 抖音 26.6.0
> com.kimen.aptvpro APTV 1.2.5
> developer.apple.wwdc-Release Developer 10.4.1
> com.meituan.imeituan 美团 12.12.402
> com.lianjia.beike 贝壳找房 2.98.30
> com.apple.AppStoreConnect Connect 1.12.2
> com.zhihu.ios 知乎 9.16.0
> com.youshang.kuaidi100 快递100 8.7.0
> com.baidu.baidunewapp 文心一言 1.5.0
> com.aihuishou.AiHuiShouApp 爱回收 6.6.3
> com.apple.TestFlight TestFlight 3.3.2
> com.qiyi.iphone 爱奇艺 14.8.0
> com.gotokeep.keep Keep 7.57.0
> com.ss.iphone.article.Video 西瓜视频 7.8.0
> com.xiaomi.mico 小爱音箱 2.2.34
> com.valvesoftware.Steam Steam 3.6.4
> com.ruguoapp.jike 即刻 7.54.1
> com.vgjump.jumper Jump 2.33.0
> cn.damai.iphone 大麦 8.6.9
> cn.12306.rails12306 铁路12306 5.7.4
> com.yum.kfc.brand 肯德基 6.4.0
> com.baidu.netdisk 百度网盘 11.57.0
> com.ss.ios.auto 懂车帝 7.7.0
> com.airbnb.app 爱彼迎 23.33
> com.exmart.HomeLink 链家 9.80.30
> com.meituan.itakeaway 美团外卖 8.10.0
> com.lingkou.app 力扣 2.10.0
> com.tencent.xin 微信 8.0.40
> com.xiaomi.mihome 米家 8.8.201
> com.tencent.weread 微信读书 7.3.7
> cn.samsclub.iphone 山姆会员商店 5.0.84
> com.baidu.tieba 百度贴吧 12.45.7
> com.bot.doubao 豆包 1.0.0
> com.google.chrome.ios Chrome 116.5845.103
> com.alicloud.smartdrive 阿里云盘 4.9.4
> app.podcast.cosmos 小宇宙 2.55.1
> com.gerinn.countdown iDays 3.43
> com.xunmeng.pinduoduo 拼多多 6.73.0
> com.laiwang.DingTalk 钉钉 7.0.50
> com.xingin.discover 小红书 8.3.1
> com.wdk.hmxs 盒马 5.72.0
> com.qunar.iphoneclient8 去哪儿旅行 5.1.1
> tv.danmaku.bilianime 哔哩哔哩 7.43.0
> com.max.xiaoheihe 小黑盒 1.3.281
> cn.fnoz.ColorCard 色卡 3.8.0
> com.cainiao.cnwireless 菜鸟 8.7.105
> com.firecore.infuse Infuse 7.5.9
> com.Ming-Zhe.circle-ios 稀土掘金 6.5.3
> com.tencent.live4iphone 腾讯视频 8.9.10
> com.tencent.ww 企业微信 4.1.9
> com.leoao.mobileapp 乐刻运动 5.25.0
> com.360buy.jdmobile 京东 168858
> com.spdb.retail.bank 浦发银行 12.1.7
> com.autonavi.amap 高德地图 12.16.1
> com.dianping.dpscope 大众点评 11.6.1
> com.tencent.portfolio 腾讯自选股 11.7.0
> com.chii.iPaper 每日壁纸杂志 0.17
> com.huolala.user 货拉拉 6.7.96
> cn.mafengwo.www 马蜂窝 10.9.9
> com.google.ios.youtube YouTube 18.32.2
> com.jqbb.youshuniao 有数鸟 1.2.0
> com.alibaba.wireless 阿里巴巴 11.4.1
> com.talkclub.iphone 妙鸭相机 1.5.2
> cn.com.scal.sichuanair 四川航空 6.8.1
> net.qihoo.360mobilesafe 360手机卫士 9.3.3
> net.csdn.CsdnPlus CSDN 6.1.3
> com.ss.iphone.article.NewsSocial 今日头条 9.0.0
> com.xiaojukeji.didi 滴滴出行 6.6.14
> com.ookla.speedtest.china Speedtest 5.0.5
> com.didapinche.taxi 嘀嗒出行 9.15.2
> tv.douyu.live 斗鱼 7.570
> com.taofang.iphone 58同城 12.19.1
> com.facebook.Facebook Facebook 428.0
> com.baidu.map 百度地图 18.8.5
> com.figma.FigmaMirror Figma 23.9.0
> com.yummygum.Billy Bobby 3.9.6
> com.boc.BOCMBCI 中国银行 8.1.9
> com.store.pa.health 平安健康保险 4.13.0
> com.taobao.taobao4iphone 淘宝 10.27.25
> com.quark.browser 夸克 6.5.2
> com.youku.YouKu 优酷 11.0.40
> com.keepassium.ios KeePassium 1.45
> net.coding.newmart 码市 4.5.0
> com.yanglei.tally 鲨鱼记账 4.41
> com.sina.heimao 黑猫投诉 2.8.7
> com.baidu.inputMethod 百度输入法 11.7.16
> com.fcbox.hiveconsumer 丰巢 4.36.0
> io.iftech.carton 小组件盒子 1.4.3
> com.jiuyu.sptcc.phonegap 上海交通卡 9.10.0
> me.ele.ios.eleme 饿了么 11.2.38
> com.linkease.linkease 易有云 1.5.0
> com.baosight.CarSharing EVCARD 5.9.0
> com.xiachufang.recipe 下厨房 238.8.6
> com.tencent.QQMusic QQ音乐 12.6.5
> HM.wristband Zepp Life 6.8.0
> com.vgn.GamePower 游戏动力 1.3.2
> com.sina.weibo 微博 13.8.2
> com.dji.golite DJI Fly 1.11.0
> ctrip.com 携程旅行 8.61.6
> com.taobao.fleamarket 闲鱼 7.12.10
> app.imone.OneWidget OneWidget 4.4.4
> cn.1hai.1haiiPhone 一嗨租车 6.9.83
> com.ownbook.notes 爱思全能版 2.2.0
> net.colorfulclouds.app.pro 彩云天气Pro 7.2.0
> com.siwuai.duapp 得物 5.24.5
> com.ziroom.ZiroomProject 自如 7.09.0
> com.cmbchina.MPBBank 招商银行 11.4.0
> com.apple.store.Jolly Apple Store 521000
> com.burbn.barcelona Threads 296.0
> com.kishan.firestickremote Fire Remote 1.6
> com.duolingo.DuolingoMobile 多邻国 6.226.0
> com.moutai.mall i茅台 1.4.6
> com.crossutility.quantumult-x Quantumult X 1.3.0
> com.netflix.Netflix Netflix 15.44.0
> com.ingka.ikea.app.cn.prod IKEA宜家家居 3.33.0
> com.bjlc.luckycoffee 瑞幸咖啡 5.1.45
> com.microsoft.smartglass Xbox 2308.2.4
> com.tencent.QQKSong 全民K歌 8.12.38
> com.zfrontier.zf-app zFrontier 1.6.11
> ```

应该是中文的问题，你暂时把设备语言调成英文应该就好了，我下个版本解决这个问题

**Comment by zackaryhuang** [comment]
已经调成英文，依旧不好使 😂

**Comment by rafa0128** [comment]
> 已经调成英文，依旧不好使 😂
实在不知道啥问题，换了种方法
可以拉一下最新代码，执行试试没问题我再发布。把python文件里面的solox模块去掉，执行debug.py文件

**Comment by rafa0128** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/24454096/f3ec9e27-981e-4550-be31-0f38e1b6ee8e)

**Comment by rafa0128** [comment]
兄弟，你有空试试2.7.3版本

**Comment by rafa0128** [comment]
下载最新版本
