### ISSUE TITLE
PK模式无法生成报告

### ISSUE THREAD

**Issue by ZSBSB** [smart-test-ti/SoloX#205]
![image](https://github.com/smart-test-ti/SoloX/assets/39560063/3dfb2ad9-f607-4aa1-8b3d-9bf0e36627ef)
如果在pk模式下，点了stop后，终端就会出现如图所示的错误，测试过程一切正常
![微信截图_20230823161048](https://github.com/smart-test-ti/SoloX/assets/39560063/069b7531-d2c7-45b2-b0d9-906a41f2d3c0)
浏览器界面错误如图

**Comment by ZSBSB** [comment]
![微信截图_20230823161048](https://github.com/smart-test-ti/SoloX/assets/39560063/a170b07c-42f7-4557-93db-189d2d52d46e)
在浏览器界面是这个错误

**Comment by rafa0128** [comment]
功能多了，很多地方做到后面忘记兼容
