### ISSUE TITLE
无法连结设备，报错如下

### ISSUE THREAD

**Issue by fkhb90** [smart-test-ti/SoloX#209]
python 3.11
solox各版本都试过了，能启动程式，但开启后一直抓不到任何手机，安卓或iOS都无法，报错如下，请帮忙看下感谢多谢！

169.254.53.183 - - [25/Aug/2023 15:26:38] "GET /static/js/highstock.js HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:38] "GET /static/js/gray.js HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:38] "GET /static/js/html2canvas.min.js HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:38] "GET /static/js/socket.io.js HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:38] "GET /static/logo/logo.png HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:39] "GET /socket.io/?EIO=3&transport=polling&t=1692948399706-0 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:39] "GET /socket.io/?EIO=3&transport=polling&t=1692948399740-2&sid=7a6a231b37af46949d1efa2f3fadf663 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:39] "POST /socket.io/?EIO=3&transport=polling&t=1692948399739-1&sid=7a6a231b37af46949d1efa2f3fadf663 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:40] "GET /socket.io/?EIO=3&transport=polling&t=1692948400302-3&sid=7a6a231b37af46949d1efa2f3fadf663 HTTP/1.1" 200 -
[E 230825 15:26:40 apis:88] not enough values to unpack (expected 2, got 1)
    Traceback (most recent call last):
      File "C:\Python311\Lib\site-packages\solox\view\apis.py", line 61, in deviceids
        deviceids = d.getDeviceIds()
                    ^^^^^^^^^^^^^^^^
      File "C:\Python311\Lib\site-packages\solox\public\common.py", line 56, in getDeviceIds
        id, state = Ids[i].strip().split('\t')
        ^^^^^^^^^
    ValueError: not enough values to unpack (expected 2, got 1)
169.254.53.183 - - [25/Aug/2023 15:26:40] "GET /device/ids?platform=Android&_=1692948399088 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:40] "GET /socket.io/?EIO=3&transport=polling&t=1692948400338-4&sid=7a6a231b37af46949d1efa2f3fadf663 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:41] "GET /socket.io/?EIO=3&transport=polling&t=1692948400989-5&sid=7a6a231b37af46949d1efa2f3fadf663 HTTP/1.1" 200 -
169.254.53.183 - - [25/Aug/2023 15:26:43] "GET /socket.io/?EIO=3&transport=polling&t=1692948403152-6&sid=7a6a231b37af469

**Comment by rafa0128** [comment]
你终端敲一下adb devices发出来看看

**Comment by fkhb90** [comment]
PS C:\Python311> adb devices
List of devices attached
VGOBT8DMZPPJX8BI        device

**Comment by rafa0128** [comment]
ios是报什么错吗？

**Comment by fkhb90** [comment]
看起来是一样的

![image](https://github.com/smart-test-ti/SoloX/assets/66230634/859f6b31-f3e0-45d6-993c-c16f5ce12bd3)

**Comment by rafa0128** [comment]
1、看日志

> PS C:\Python311> adb devices List of devices attached VGOBT8DMZPPJX8BI device

VGOBT8DMZPPJX8BI device中间是一个空格还是\t

**Comment by rafa0128** [comment]
是空格还是\t，你看就好

**Comment by fkhb90** [comment]
不是很懂，我要去哪里看日志，device 中间没有空格或\t
![image](https://github.com/smart-test-ti/SoloX/assets/66230634/80a1da81-2651-4d31-8afa-d93d1ff7ffa6)

**Comment by rafa0128** [comment]
> 不是很懂，我要去哪里看日志，device 中间没有空格或\t ![image](https://user-images.githubusercontent.com/66230634/263216407-80a1da81-2651-4d31-8afa-d93d1ff7ffa6.png)

看上去安卓应该没问题，你在执行的路径敲一下adb devices看看有没连接的设备，日志里面有没有waiting for device?

**Comment by fkhb90** [comment]
这就是敲adb devices的结果
确实是有抓到devices的

**Comment by fkhb90** [comment]
我换了三部安卓机，都是报相同的错

**Comment by rafa0128** [comment]
> 我换了三部安卓机，都是报相同的错

看不出问题
