### ISSUE TITLE
APP内同样的操作，perfdog的FPS均值是49，solox的FPS均值是3。。。。

### ISSUE THREAD

**Issue by Doraemon-zh-CN** [smart-test-ti/SoloX#217]
python：3.10.0
solox：2.7.5
我看控制台也没报错日志
perfdog：
![微信图片_20230908230550](https://github.com/smart-test-ti/SoloX/assets/42923634/4437cb1a-dd01-4416-9cf2-7dcfca1b1d22)
solox：
![微信图片_20230908230038](https://github.com/smart-test-ti/SoloX/assets/42923634/3fa38103-c021-4858-99f4-328d57e5c959)

**Comment by zackaryhuang** [comment]
我甚至没打开 APP 就有 FPS 数据了，数据差异太大了，感觉在逗我玩 😂

**Comment by rafa0128** [comment]
啥场景？一般1-3的值都是异常数据

**Comment by rafa0128** [comment]
你能用perfdog为啥用solox

**Comment by Doraemon-zh-CN** [comment]
perfdog白嫖的15分钟啊，就进入APP后静置的场景，solopi也能出数据，问了一下研发好像说是gfxinfo获取不到SurfaceView

**Comment by rafa0128** [comment]
> perfdog白嫖的15分钟啊，就进入APP后静置的场景，solopi也能出数据，问了一下研发好像说是gfxinfo获取不到SurfaceView

gfxinfo和surfaceview是两种方式，首页关掉SurfaceView开关就切换gfxinfo的收集方式了，但是手机开发者要设置以下gfxinfo选项，你可以都试试。perfdog和solopi都是用原生api收集的，solox是adb，肯定原生api会准确一些

**Comment by rafa0128** [comment]
安装2.7.6
