### ISSUE TITLE
鸿蒙4.0系统提示连接失败

### ISSUE THREAD

**Issue by aovenus** [smart-test-ti/SoloX#223]
![image](https://github.com/smart-test-ti/SoloX/assets/89002625/6cbda22e-4aa5-4f1b-ab71-1da9e1913d08)

![image](https://github.com/smart-test-ti/SoloX/assets/89002625/9f6f08e1-5b17-4a9b-8ba4-d0cdac3077aa)

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/blob/master/FAQ.md#4%EF%B8%8F%E2%83%A3-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%89%8B%E6%9C%BA%E5%B7%B2%E7%BB%8F%E8%BF%9E%E6%8E%A5%E7%94%B5%E8%84%91%E4%BD%86%E6%98%AF%E8%BF%98%E6%98%AF%E6%98%BE%E7%A4%BA%E8%BF%9E%E6%8E%A5%E5%A4%B1%E8%B4%A5-

**Comment by aovenus** [comment]
已解决，谢谢！
