### ISSUE TITLE
采集的system CPU 指标接近100%，对比其它工具，实际并未到100%

### ISSUE THREAD

**Issue by zzw558** [smart-test-ti/SoloX#224]
测试机型：VIVO X80
测试app： 今日头条
CPU指标中，system 一直接近100%，使用其它工具监测 全局CPU并未达到100%
![img_v2_0185cf10-bf10-4c4d-b6b1-f5d2f903082g](https://github.com/smart-test-ti/SoloX/assets/26242903/ea49cb94-674e-41d8-85fb-22c9ab3fc26c)

**Comment by rafa0128** [comment]
其实我也觉得奇怪，我已经按照标准的计算方法了。你看看perfdog是多少来着

**Comment by zzw558** [comment]
> 其实我也觉得奇怪，我已经按照标准的计算方法了。你看看perfdog是多少来着

Solopi 测试1个小时全局使用率CPU在48%左右；
另外还有个问题大佬看能不能优化一下，运行40分钟的数据分析结果时浏览器基本就卡死了，电脑配置不算低 i7-8C-16G

**Comment by chimianshaonian** [comment]
我这里通过api测试了5分，sys的cpu也解决100%，而曲线图中超过100% 的也不少
用的是华为m6 
![image](https://github.com/smart-test-ti/SoloX/assets/73635546/aede7cd1-becc-4b4d-9d8f-db191c9bb1cc)

**Comment by chimianshaonian** [comment]
然后我试了下api和界面两种方式测了下，两种方式收集的数据，其中CPU差距还是比较明显，APP操作基本一样，都是开始收集数据后，APP运行。
![image](https://github.com/smart-test-ti/SoloX/assets/73635546/e4d38b6d-d761-4a12-bb43-70e71d54f195)

**Comment by rafa0128** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/24454096/626c0ad1-1af9-41b2-9b13-2168f92ce23d)
我自己跑了今日头条看上去挺正常的

**Comment by chimianshaonian** [comment]
下午我再试下

**Comment by chimianshaonian** [comment]
刚又试了一下，还是一样，但这次fps反而都为0
![image](https://github.com/smart-test-ti/SoloX/assets/73635546/6ef31e03-b624-425a-a55b-7f1d1af0ec0f)
