### ISSUE TITLE
請問一下此應用支持安卓13嗎
因為他連結安卓13後就無法選擇app了

### ISSUE THREAD

**Issue by Mamgo1128** [smart-test-ti/SoloX#225]

**Comment by rafa0128** [comment]
我不信，晒出你的证据

**Comment by Mamgo1128** [comment]
![image-26.png](https://github.com/smart-test-ti/SoloX/assets/124562166/ccf063a8-1a02-44f3-87b9-3644cfefce3e)

**Comment by Mamgo1128** [comment]
左邊沒辦法選擇app

**Comment by rafa0128** [comment]
执行adb shell pm list package，发出来看一下

**Comment by Mamgo1128** [comment]
不好意思請問要在哪裡執行：）

**Comment by Mamgo1128** [comment]
![image25](https://github.com/smart-test-ti/SoloX/assets/124562166/998dd636-4621-43bd-9002-80893d9ab8ee)

**Comment by rafa0128** [comment]
再分别试试这两个：
adb shell pm list packages --user 0
adb shell pm list packages --user 150

**Comment by Mamgo1128** [comment]
> 
![image](https://github.com/smart-test-ti/SoloX/assets/124562166/7e5761ee-3c96-4947-b2a6-1126bf467681)

**Comment by Mamgo1128** [comment]
![image](https://github.com/smart-test-ti/SoloX/assets/124562166/a73cf9c0-6aef-4583-af02-73dbf6120a50)

**Comment by rafa0128** [comment]
ok，下个版本解决

**Comment by Mamgo1128** [comment]
好的 感謝你

**Comment by Mamgo1128** [comment]
請問這是修好了嗎

**Comment by rafa0128** [comment]
> 請問這是修好了嗎

安装2.7.9

**Comment by Mamgo1128** [comment]
請問按下開始後 手機一直顯示充電畫面且一直震動是正常的嗎
