### ISSUE TITLE
No such file or directory:....\\solox\\public\\config.json'

### ISSUE THREAD

**Issue by katyhudson** [smart-test-ti/SoloX#242]
python:311
solox:2.8.3
D:\Python311\python.exe D:/Python311/Lib/site-packages/solox/solox-tzt.py
[I 231127 11:04:07 common:155] Connected devices: ['00008101-001238D10A00001E']
[I 231127 11:04:07 common:874] stop scrcpy process
[E 231127 11:04:08 apm:612] [Errno 2] No such file or directory: 'D:\\Python311\\Lib\\site-packages\\solox\\public\\config.json'
    Traceback (most recent call last):
      File "D:\Python311\Lib\site-packages\solox\public\apm.py", line 592, in collectAll
        self.start()
      File "D:\Python311\Lib\site-packages\solox\public\apm.py", line 432, in start
        config_json = json.loads(open(file=cls.CONIFG_PATH, mode='r').read())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Python311\\Lib\\site-packages\\solox\\public\\config.json'
[I 231127 11:04:08 apm:614] End of testing

**Comment by katyhudson** [comment]
> 忘记打包这个配置文件了，2.8.4已解决

[I 231127 13:38:00 common:155] Connected devices: ['00008101-001238D10A00001E']
[I 231127 13:38:00 common:247] Clean up useless files ...
[I 231127 13:38:00 common:874] stop scrcpy process
[I 231127 13:38:00 common:254] Clean up useless files success
error: device 'None' not found
[W 231127 13:38:01 common:107] com.tzt.iphone2: no pid found
[E 231127 13:38:01 apm:291] [Network] com.tzt.iphone2 : No process found

**Comment by katyhudson** [comment]
> 忘记打包这个配置文件了，2.8.4已解决

大佬执行时长在哪配置了

**Comment by rafa0128** [comment]
> > 忘记打包这个配置文件了，2.8.4已解决
> 
> 大佬执行时长在哪配置了

去掉了

**Comment by katyhudson** [comment]
> > > 忘记打包这个配置文件了，2.8.4已解决
> > 
> > 
> > 大佬执行时长在哪配置了
> 
> 去掉了

python api如何自动停止并生成报告。

**Comment by rafa0128** [comment]
我还是加上duration吧，等下个版本。这次给你们停止的方法，就是为了给你们自定义怎么停止

**Comment by katyhudson** [comment]
> > > 忘记打包这个配置文件了，2.8.4已解决
> > 
> > 
> > [I 231127 13:38:00 common:155] Connected devices: ['00008101-001238D10A00001E'] [I 231127 13:38:00 common:247] Clean up useless files ... [I 231127 13:38:00 common:874] stop scrcpy process [I 231127 13:38:00 common:254] Clean up useless files success error: device 'None' not found [W 231127 13:38:01 common:107] com.tzt.iphone2: no pid found [E 231127 13:38:01 apm:291] [Network] com.tzt.iphone2 : No process found
> 
> 日志不是说了吗

用python api会报这个错误。无论是用win还是用mac

**Comment by rafa0128** [comment]
这个是因为你没启动app吧？一直报吗？

**Comment by katyhudson** [comment]
> 这个是因为你没启动app吧？一直报吗？还有你的id有点像ios，你是不是platform传了Android？ios是没有检测进程的

一直启动着app的。是ios platform='iOS'。
如果用界面去运行ios，15分钟左右，api会报错
[I 231128 14:15:59 common:854] stop scrcpy process
[I 231128 14:16:00 common:234] Clean up useless files success
[E 231128 14:16:03 apis:214] get cpu failed
[E 231128 14:16:03 apis:215] connection closed
    Traceback (most recent call last):
      File "D:\Python311\Lib\site-packages\solox\view\apis.py", line 211, in getCpuRate
        appCpuRate, systemCpuRate = cpu.getCpuRate()
                                    ^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\apm.py", line 131, in getCpuRate
        appCpuRate, systemCpuRate = self.getAndroidCpuRate(noLog) if self.platform == Platform.Android else self.getiOSCpuRate(noLog)
                                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\apm.py", line 122, in getiOSCpuRate
        sysCpuRate = round(float(apm.getPerformance(apm.cpu)[1]), 2)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\apm.py", line 416, in getPerformance
        perf_value = perf.start(self.pkgName, callback=self.callback)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\_iosPerf.py", line 321, in start
        _perfValue = self._thread_start(callback)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\_iosPerf.py", line 341, in _thread_start
        _perfValue = append_data(self._wg, self._stop_event, it, callback, self._perfs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\solox\public\_iosPerf.py", line 273, in append_data
        for _type, data in idata:
      File "D:\Python311\Lib\site-packages\solox\public\_iosPerf.py", line 238, in iter_cpu
        for minfo in _iter_complex_cpu_memory(d, rp):  # d.iter_cpu_mem(bundle_id):
      File "D:\Python311\Lib\site-packages\solox\public\_iosPerf.py", line 157, in _iter_complex_cpu_memory
        for info in ts.iter_cpu_memory():
      File "D:\Python311\Lib\site-packages\tidevice\_instruments.py", line 919, in iter_cpu_memory
        channel_id = self.make_channel(InstrumentsService.Sysmontap)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\tidevice\_instruments.py", line 318, in make_channel
        result = self.call_message(0, '_requestChannelWithCode:identifier:', aux)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\tidevice\_instruments.py", line 363, in call_message
        return self.wait_reply(_id).result
               ^^^^^^^^^^^^^^^^^^^^
      File "D:\Python311\Lib\site-packages\tidevice\_instruments.py", line 568, in wait_reply
        raise MuxError("connection closed")
    tidevice.exceptions.MuxError: connection closed
Process SpawnPoolWorker-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python311\Lib\multiprocessing\pool.py", line 114, in worker
    task = get()
           ^^^^^

**Comment by rafa0128** [comment]
你这个又不是上面的问题啊，connection closed，tidevice连接失败了。

**Comment by katyhudson** [comment]
> 你这个又不是上面的问题啊，connection closed，tidevice连接失败了。

![image](https://github.com/smart-test-ti/SoloX/assets/24410664/f15b40a6-a869-4f92-bfc1-b1eb8a1043ef)

**Comment by katyhudson** [comment]
> 你这个又不是上面的问题啊，connection closed，tidevice连接失败了。

2.8.5最新版本

**Comment by katyhudson** [comment]
> 这个是因为你没启动app吧？一直报吗？还有你的id有点像ios，你是不是platform传了Android？ios是没有检测进程的

只报了一次在开始阶段
[I 231128 14:26:11 common:854] stop scrcpy process
[I 231128 14:26:11 common:234] Clean up useless files success
error: device 'None' not found
[W 231128 14:26:12 common:107] com.tzt.iphone2: no pid found
[E 231128 14:26:12 apm:291] [Network] com.tzt.iphone2 : No process found

**Comment by rafa0128** [comment]
ok，发现问题

**Comment by katyhudson** [comment]
> ok，发现问题

大佬辛苦！

**Comment by katyhudson** [comment]
> > ok，发现问题
> 
> 大佬辛苦！
> 
> 界面应该没有问题，上面tidevice连接失败，我这边控制不了

用mac运行会稳定些吗

**Comment by katyhudson** [comment]
> ok，发现问题
-----分割线------
使用mac界面运行，会有 /bin/sh:adb:command not found   server error问题，跟win端是不是一样的问题
![image](https://github.com/smart-test-ti/SoloX/assets/24410664/36aac441-e5d3-482b-ad1c-94a150280137)
![image](https://github.com/smart-test-ti/SoloX/assets/24410664/8be784bc-47e7-485f-973f-9263ffb4db03)
![image](https://github.com/smart-test-ti/SoloX/assets/24410664/803bb59b-8e1c-4587-a2b8-62a791429038)

**Comment by rafa0128** [comment]
别在这里说了，还能用吗？

**Comment by katyhudson** [comment]
> 别在这里说了，还能用吗？

不能用。只能获取电池了。其他数据获取不了。也无法停止

**Comment by rafa0128** [comment]
确定是2.8.5报的吗？有点像老版本才会有这个问题

**Comment by katyhudson** [comment]
> 确定是2.8.5报的吗？有点像老版本才会有这个问题 这个问题我以前解决过，是因为安卓加了进程这个选项，ios没有也传过去了

是2.8.5 之前用的2.7版本没有出现过

**Comment by rafa0128** [comment]
看你的界面是2.6的
