### ISSUE TITLE
会不会增加GPU和磁盘io监测

### ISSUE THREAD

**Issue by 1one4** [smart-test-ti/SoloX#246]
目前GPU和磁盘IO读写两个指标，不少企业都有这两个指标的要求，是否考虑增加以下

**Comment by 1one4** [comment]
另外还有内存的各个指标，比如java heap、Java Heap、Native Heap、Code、Stack、Graphics、 Private Othe、System这些数据的采集

**Comment by rafa0128** [comment]
> 目前GPU和磁盘IO读写两个指标，不少企业都有这两个指标的要求，是否考虑增加以下

安卓的gpu弄不了，需要root权限才可以。而且目前市面支持的工具兼容的机器大多是高通的芯片的设备，很少机型的。大部分是oppo、vivo的。
可以看看perfdog的：https://bbs.perfdog.qq.com/detail-195.html

磁盘的看看

**Comment by rafa0128** [comment]
> 另外还有内存的各个指标，比如java heap、Java Heap、Native Heap、Code、Stack、Graphics、 Private Othe、System这些数据的采集

可以加，下个版本。

**Comment by 1one4** [comment]
> > 另外还有内存的各个指标，比如java heap、Java Heap、Native Heap、Code、Stack、Graphics、 Private Othe、System这些数据的采集
> 
> 可以加，下个版本。

大佬，下个版本大概什么时候更新呀

**Comment by rafa0128** [comment]
月内，一个月一个版本，年底该忙绩效了，哈哈😄
