### ISSUE TITLE
Android手机，收集数据时，手机一直在连接的状态，感觉就是adb一直在无限重新连接，数据收集正常

### ISSUE THREAD

**Issue by qangcheng** [smart-test-ti/SoloX#262]
Android手机，收集数据时，手机一直在连接的状态，感觉就是adb一直在无限重新连接，数据收集正常，没有看到报错
机型：galaxy A60
版本：Android11

连接后一直adb无线重新连接，手机一直发出连接上的声音和充电的UI。

**Comment by rafa0128** [comment]
https://github.com/smart-test-ti/SoloX/issues/213
