### ISSUE TITLE
页面无设备

### ISSUE THREAD

**Issue by lingfeng257** [smart-test-ti/SoloX#27]
默认打开的http://0.0.0.0:5000 无法访问，根据cmd提示打开了http://192.168.0.65:5000 ，可正常访问，但是一直没有设备。而在cmd里面是可以查询到设备的

**Comment by rafa0128** [comment]
不能访问的问题下个版本会修复的哈，一直没有设备，你使用adb devices有吗

**Comment by lingfeng257** [comment]
adb devices里面可以查到设备，也可以跑monkey

**Comment by lingfeng257** [comment]
![image](https://user-images.githubusercontent.com/25917727/178732738-3454f0c5-dcce-4cf6-a1cf-9f73b9efc228.png)

**Comment by rafa0128** [comment]
> adb devices里面可以查到设备，也可以跑monkey

请更新最新版本哈，做了一些处理解决该问题，看看你那边好了没有：pip3 install -U solox

**Comment by rafa0128** [comment]
> 已经可以发现设备了，但是启动后报错，具体如下：
> 
> ![image](https://user-images.githubusercontent.com/25917727/178977102-d1bf85b2-7aa2-4b8a-92e3-93bc193236b2.png)

目前没有windows机器可以调试，下个版本会加上更详细的报错日志来定位解决问题哈。
