### ISSUE TITLE
运行命令后只执行一句就结束了

### ISSUE THREAD

**Issue by Popstarz** [smart-test-ti/SoloX#272]
<img width="703" alt="image" src="https://github.com/smart-test-ti/SoloX/assets/46955625/4d3521d5-8d35-4807-bd48-6c9cae988a28">

**Comment by rafa0128** [comment]
python -m solox --host={ip} --port={port}，自己指定ip和端口启动试试

**Comment by Popstarz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的来信，谢谢。

**Comment by Popstarz** [comment]
<img width="890" alt="image" src="https://github.com/smart-test-ti/SoloX/assets/46955625/8bd4fcf8-6338-4dfe-b3c8-3ecf3ac63ffe">
还是不行，还有其他的可能吗

**Comment by rafa0128** [comment]
import webbrowser

webbrowser.open('www.baidu.com')

你电脑执行这句代码试试

**Comment by Popstarz** [comment]
还真是，这个我也是执行完，没反应
<img width="1068" alt="image" src="https://github.com/smart-test-ti/SoloX/assets/46955625/66e242a6-ca58-4a15-96d8-5fa0c06a0865">

**Comment by rafa0128** [comment]
你自己装个chrome设置成默认浏览器

**Comment by rafa0128** [comment]
实在不行就换电脑执行吧

**Comment by Popstarz** [comment]
好的，我换windows试试

**Comment by Y998s** [comment]
我这边也是无法跳转出游览器怎么解决

**Comment by Popstarz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的来信，谢谢。

**Comment by Popstarz** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的来信，谢谢。
