### ISSUE TITLE
浏览器无法拉起的solox页面，显示无法访问此网站

### ISSUE THREAD

**Issue by ktsHL** [smart-test-ti/SoloX#273]
D:\Huawei\Download\solox-2.5.3\solox-2.5.3>python -m solox --host=127.0.0.1 --port=5127
[I 240326 15:02:51 web:141] start solox server...
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Serving Flask app 'solox.web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[I 240326 15:02:53 web:144] Running on http://127.0.0.1:5127/?platform=Android&lan=en (Press CTRL+C to quit)
![image](https://github.com/smart-test-ti/SoloX/assets/164996442/d594262f-fa57-4aed-8992-5f77614fad2b)
![image](https://github.com/smart-test-ti/SoloX/assets/164996442/66a6161e-a312-46b7-8fdf-a8393f39f780)
![image](https://github.com/smart-test-ti/SoloX/assets/164996442/55a84461-f47a-4744-a7ef-1870b29b02d5)

**Comment by rafa0128** [comment]
下载新版本，还有看看你电脑的防火墙是不是限制

**Comment by ktsHL** [comment]
> 下载新版本，还有看看你电脑的防火墙是不是限制

我的python版本是3.7，按照你的使用指导只能下载安装2.5.4以下的，我安装的是2.5.3的 应该是没问题的

**Comment by rafa0128** [comment]
你这个应该是电脑限制了，你自己起个flask服务看看能不能访问。旧版本很少功能的准确度也不高，下载最新python版本

**Comment by ktsHL** [comment]
安装新版本就可以了
