### ISSUE TITLE
appCpuRate计算问题

### ISSUE THREAD

**Issue by TieZhuNo1** [smart-test-ti/SoloX#278]
我使用小米和荣耀平板都是8核心设备测试，获取进程数据
[I 240514 10:41:48 apm:571] cpu: {'appCpuRate': 2.76, 'systemCpuRate': 23.91}
但是adb shell top显示的是
<img width="621" alt="image" src="https://github.com/smart-test-ti/SoloX/assets/57322990/4e79d741-a263-4a16-9937-f9ac852438dd">
感觉systemCpuRate乘以8和top命令基本一致
但是appCpuRate貌似要乘以16才和top命令基本一致，这是为什么呢，能麻烦看看吗

**Comment by rafa0128** [comment]
那计算可能有点问题，有和perfdog比较过吗？我们对标的是perfdog

**Comment by TieZhuNo1** [comment]
> 那计算可能有点问题，有和perfdog比较过吗？我们对标的是perfdog

害，主要perfdog收费后也没法试用比较了，大哥你能用手上的设备尝试一下吗，感谢！

**Comment by rafa0128** [comment]
> > 那计算可能有点问题，有和perfdog比较过吗？我们对标的是perfdog
> 
> 害，主要perfdog收费后也没法试用比较了，大哥你能用手上的设备尝试一下吗，感谢！

改了，等新版本

**Comment by TieZhuNo1** [comment]
> > > 那计算可能有点问题，有和perfdog比较过吗？我们对标的是perfdog
> > 
> > 
> > 害，主要perfdog收费后也没法试用比较了，大哥你能用手上的设备尝试一下吗，感谢！
> 
> 改了，等新版本

给大佬打call！！！
