### ISSUE TITLE
It doesn't work on the secondary process

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#28]
It just works on the main process, it doesn't work on the secondary process(subprocess), just like Wechat applet,maybe all of the data about the secondary process is wrong . so many apps have the secondary process now, it's better to support secondary process, it's better to show the total data of phone,so that we can avoid fatal mistakes.

![20220713_233847](https://user-images.githubusercontent.com/58470642/178776284-2be11302-a584-401f-a47f-f75144937f7a.jpg)

**Comment by rafa0128** [comment]
谢谢反馈，会找时间看看小程序的收集问题

**Comment by LRF520** [comment]
It is indeed a difficulty, because many software runs at the same time as the main process and many sub processes, so the actual performance data is much larger. Most of the time, the child process runs in the foreground and the main process runs in the background, so in fact, the main process may not occupy too many obvious resources. Therefore, collecting data of the main process and all sub processes at the same time is relatively complete data, but it is not absolutely complete data.

**Comment by LRF520** [comment]
Congratulations on completing the development of IOS !!!
