### ISSUE TITLE
The time of abscissa is different

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#29]
The time of abscissa is different，It cannot have the effect of simultaneous comparison.

![image](https://user-images.githubusercontent.com/58470642/179194370-85e2e8e7-1547-48f0-ad23-abbf4f90d2fa.png)

**Comment by rafa0128** [comment]
这里的话因为每个指标拿到数据的速度不一样的，这里每个指标都是独立进程去收集的，所以时间没有统一。如果硬要统一时间智能强制把读取的快的数据也放到和最后的数据一起写入，这样反而收集慢了得不偿失。

**Comment by LRF520** [comment]
I think writing data at the same time can convince the team of the accuracy of the data, like this:

![iOS-perf-3x](https://user-images.githubusercontent.com/58470642/179402599-a4a5c8e7-3df1-4e08-b67c-e334c2fac5f5.gif)
