### ISSUE TITLE
tidevice error

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#30]
![image](https://user-images.githubusercontent.com/58470642/179404338-8664c5ad-fc9b-41e5-b23d-97edcd463b74.png)

**Comment by rafa0128** [comment]
没有windows机器，不知道tidevice的支持是怎么样的，更新solox最新版本的时候没有报错了，试试自己单独装下pip3 install -U tidevice，这个是用来读取iOS设备信息的
