### ISSUE TITLE
It is not supported to test two mobile phones at the same time

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#31]
It is not supported to test two mobile phones at the same time. If only Android and IOS could be tested at the same time.

![20220718_231949](https://user-images.githubusercontent.com/58470642/179545374-03bdb2f7-6d59-445a-8288-252d6a16c67b.jpg)

**Comment by rafa0128** [comment]
如果同时开几个窗口，对pc机器的性能要求会比较高，后续再想办法优化这里
