### ISSUE TITLE
The image is notched and discontinuous

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#32]
Historical data cannot adaptively change the data range:

![20220718_235126](https://user-images.githubusercontent.com/58470642/179552044-3279b10e-db20-4cee-92a5-2c404d3822fa.jpg)
![20220718_235144](https://user-images.githubusercontent.com/58470642/179552066-f4e30416-d5d5-4a8c-a74c-b35d80ecbac3.jpg)

**Comment by rafa0128** [comment]
暂时未发现

**Comment by LRF520** [comment]
Can meet daily needs
