### ISSUE TITLE
The units of data are inconsistent, and the sorting of report charts may be a little disordered

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#33]
The units of data are inconsistent, and the sorting of report charts may be a little disordered. It would be better to keep the same sorting as APM pages.

![20220719_010228](https://user-images.githubusercontent.com/58470642/179564525-0dc88622-e606-44bb-8aad-b7b04e8f0a7f.jpg)
![20220719_002105](https://user-images.githubusercontent.com/58470642/179558088-c743c4ab-32f4-4016-b5d4-f0b1464d3f98.jpg)
![20220719_010300](https://user-images.githubusercontent.com/58470642/179564572-f62784d1-1600-4f4f-b9e6-10f0fb5ec243.jpg)
![20220719_002218](https://user-images.githubusercontent.com/58470642/179558117-0fabb554-204d-4362-bc57-e072c00dbd27.jpg)
![20220719_002430](https://user-images.githubusercontent.com/58470642/179558164-37c7100e-6890-4b43-9214-f1d9a93e1af2.jpg)

**Comment by rafa0128** [comment]
> The units of data are inconsistent, and the sorting of report charts may be a little disordered. It would be better to keep the same sorting as APM pages.
> 
> ![20220719_010228](https://user-images.githubusercontent.com/58470642/179564525-0dc88622-e606-44bb-8aad-b7b04e8f0a7f.jpg) ![20220719_002105](https://user-images.githubusercontent.com/58470642/179558088-c743c4ab-32f4-4016-b5d4-f0b1464d3f98.jpg) ![20220719_010300](https://user-images.githubusercontent.com/58470642/179564572-f62784d1-1600-4f4f-b9e6-10f0fb5ec243.jpg) ![20220719_002218](https://user-images.githubusercontent.com/58470642/179558117-0fabb554-204d-4362-bc57-e072c00dbd27.jpg) ![20220719_002430](https://user-images.githubusercontent.com/58470642/179558164-37c7100e-6890-4b43-9214-f1d9a93e1af2.jpg)

下个版本修复，没注意弄错了
