### ISSUE TITLE
cpu的计算方式和top的方式得出的结果差距很大

### ISSUE THREAD

**Issue by huangkunsds** [smart-test-ti/SoloX#34]

**Comment by rafa0128** [comment]
目前除了fps和jank，其他的指标是参考这里的收集方法：https://developer.aliyun.com/article/780317#slide-6
自己也没有横向对比过，如果solox的数据有问题的话，可以提问题哈。

**Comment by rafa0128** [comment]
> _No description provided._

top的计算方式你是单核和还是多核的？多核的要除以核数再比较看看
