### ISSUE TITLE
The IOS connection frequently reports errors. 

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#39]
The IOS connection frequently reports errors, which is very unstable. Once an error is reported, the data transmission will stop and will not recover automatically.

![20220803_165206](https://user-images.githubusercontent.com/58470642/182567361-f4eb1d94-4a72-4346-854d-fa1a8db3e4b4.jpg)

**Comment by rafa0128** [comment]
报错的是因为tidevice出现的异常，solox做了不阻碍继续收集
