### ISSUE TITLE
The network speed calculation of IOS is wrong. 

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#40]
The network speed calculation of IOS is wrong. It may be the unit conversion error. It is recommended to check the upload speed and download speed of IOS. I estimate that the data of Android is relatively normal, so referring to the data calculation method of Android may get the correct IOS network speed data.

![20220806_014759](https://user-images.githubusercontent.com/58470642/183133450-af40e261-b735-4ff3-99d4-f3981c14685e.jpg)
![20220806_014721](https://user-images.githubusercontent.com/58470642/183133467-5021f591-af22-4488-9b8d-d22489cc9977.jpg)
![20220806_014853](https://user-images.githubusercontent.com/58470642/183133479-f8b61733-0bd8-4d9e-9811-2b9a7dafef68.jpg)

**Comment by rafa0128** [comment]
这边跑下来看了计算应该没有问题，麻烦检查一下是否有个别脏数据

**Comment by LRF520** [comment]
> 这边跑下来看了计算应该没有问题，麻烦检查一下是否有个别脏数据


I'm sure IOS's statistics on the real-time network speed of a process are wrong. My maximum actual network speed is less than 2310 KB/ s.

![20220808_141202](https://user-images.githubusercontent.com/58470642/183351654-9b6fb5ab-756d-47e6-a223-830c1a6dc96b.jpg)

![20220808_141334](https://user-images.githubusercontent.com/58470642/183351680-9b644332-27b0-4a36-ab45-d3e5bd8a55d1.jpg)

**Comment by LRF520** [comment]
> 这边跑下来看了计算应该没有问题，麻烦检查一下是否有个别脏数据

There are also many mistakes, and it can't stop at all.

![20220808_142157](https://user-images.githubusercontent.com/58470642/183352697-b8976904-c9aa-4a4a-a0ab-01a9e4960e4c.jpg)
