### ISSUE TITLE
The real-time network speed data of Android is also wrong

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#41]
The real-time network speed data of Android is also wrong. What is collected now is the real-time network speed of the whole mobile phone, not the real-time network speed of a certain process.

![20220806_133934](https://user-images.githubusercontent.com/58470642/183235906-e3d8888c-ad15-4f52-8291-655b6cbb0c72.jpg)

**Comment by rafa0128** [comment]
看代码方法目前应该是计算app每秒的损耗流量了，不是设备的

**Comment by LRF520** [comment]
> 看代码方法目前应该是计算app每秒的损耗流量了，不是设备的

I'm sure that Android's statistics on the real-time network speed of a process are wrong. If I'm testing wechat or UC browser, I put wechat or UC browser in the background and they haven't downloaded anything. At this time, I open Speedtest to test the maximum download speed and upload speed of the mobile phone. At this time, what solox reads is the total network speed of the mobile phone, not the real-time network speed of wechat or UC browser.

The same is true for IOS.

I have changed three computers and mobile phones to verify this problem.

![20220808_115303](https://user-images.githubusercontent.com/58470642/183336191-0a0bd2d2-46e3-4a67-a959-a3703f7b2075.jpg)
