### ISSUE TITLE
It is suggested that all data collection time should be changed to 3 seconds or 5 seconds

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#42]
The current data acquisition time interval is once every 10 seconds? It is suggested that all data collection time should be changed to 3 seconds or 5 seconds, which is very helpful to debug the correctness of these data. Too long a collection time interval will lead to too much data loss and it is difficult to analyze the real results of the data.

**Comment by rafa0128** [comment]
不是哦，代码是1-2秒收集一次，但是开了比较多的进程去收集，可能设备配置不好的话会慢一点，我的mac其实速度还行2秒左右吧

**Comment by LRF520** [comment]
right~~~
