### ISSUE TITLE
It is recommended to give the system version range of Android and IOS on the description page.

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#44]
It is recommended to give the system version range of Android and IOS on the description page.

![20220808_162631](https://user-images.githubusercontent.com/58470642/183374896-91779d5b-be16-4202-995f-29edd74ec1a2.jpg)

**Comment by rafa0128** [comment]
后续再慢慢整理一些细节的提示，先把大头功能做好

**Comment by LRF520** [comment]
waiting~~~
