### ISSUE TITLE
The FPS real-time statistics of IOS is wrong

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#45]
The FPS real-time statistics of IOS is wrong, because my app has been placed in the background and there is no operation, but solox has a very high FPS. It only counts the FPS of the current interface and does not count the FPS of a process.

![20220808_172717](https://user-images.githubusercontent.com/58470642/183386618-553ab2e8-2a7c-4c91-9a84-8031b3f8bb7a.jpg)

**Comment by rafa0128** [comment]
能对比一下perfdog吗？使用了Xcode-Instruments-CoreAnimation看是差不多的

**Comment by LRF520** [comment]
> 能对比一下perfdog吗？使用了Xcode-Instruments-CoreAnimation看是差不多的

Theoretically, if the program has been placed in the background, the FPS data should not be counted. However, IOS always has a large FPS, so I think IOS only collects the FPS of the current mobile phone interface, not the FPS of a certain software itself.

However, the FPS acquisition of Android is aimed at the FPS of a certain software itself.
