### ISSUE TITLE
FPS一直是1

### ISSUE THREAD

**Issue by kalan898** [smart-test-ti/SoloX#46]
请问FPS的值为什么一直是1呢，有没有遇到相问题的小伙伴啊

**Comment by rafa0128** [comment]
> 请问FPS的值为什么一直是1呢，有没有遇到相问题的小伙伴啊

如果是android的话，请检查下有没有打开“GPU呈现模式分析”选择在“adb shell dumpsys gfxinfo”中

**Comment by kalan898** [comment]
> > 请问FPS的值为什么一直是1呢，有没有遇到相问题的小伙伴啊
> 
> 如果是android的话，请检查下有没有打开“GPU呈现模式分析”选择在“adb shell dumpsys gfxinfo”中

开了，还是这个样子

**Comment by rafa0128** [comment]
> > > 请问FPS的值为什么一直是1呢，有没有遇到相问题的小伙伴啊
> > 
> > 
> > 如果是android的话，请检查下有没有打开“GPU呈现模式分析”选择在“adb shell dumpsys gfxinfo”中
> 
> 开了，还是这个样子

fps是1一般是只取到更新时间16666666
不同的机型厂商可能有兼容问题，你执行adb shell dumpsys SurfaceFlinger --latency <activityname> ，给出数据我看看，如果有很多行数据就正常
activityname是你的app当前界面的activity
