### ISSUE TITLE
Android failed to collect data, and an error was reported during operation

### ISSUE THREAD

**Issue by LRF520** [smart-test-ti/SoloX#47]
Android failed to collect data, and an error was reported during operation

![20220815_110539](https://user-images.githubusercontent.com/58470642/184570552-a0f4c234-3c89-43d8-860c-5102b71731b7.jpg)

![image](https://user-images.githubusercontent.com/58470642/184570595-8f5745ba-9b8d-4f2e-a006-1da6bbc2bb6b.png)

**Comment by rafa0128** [comment]
请问是必现吗？

**Comment by LRF520** [comment]
> 请问是必现吗？

yes！

**Comment by rafa0128** [comment]
> > 请问是必现吗？
> 
> yes！

看代码出现这种情况一般有两种：
1、在你收集的过程中，设备连接出现问题
2、你收集的app进程没起来

**Comment by LRF520** [comment]
try again~~~
