### ISSUE TITLE
Requirements for creating an issue？（如何给SoloX提问题？不符合规范就直接关闭不解答了，还有麻烦仔细看完READEME再提问题）

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#49]
Title：
【BUG】..... ：The content of the bug （碰到什么BUG，一定要有平台、机型、app、日志等）
【Feature】....：The content of the feature （希望增加什么功能）
【QA】....: Not understanding the function （对功能不理解，需要答疑）

Note：If it is a bug, it must include platform, model, and app （必须说明这么运行的、平台、机型、app、日志等）

**Comment by xienova** [comment]
【BUG】:测试执行后，电源电量一直显示 正在充电的图标，只能重启后才消失。

**Comment by hnxaky** [comment]
在连接的时候，出现了host error
