### ISSUE TITLE
Android 使用提示 no found app process，不知道是不是我机型有问题

### ISSUE THREAD

**Issue by gengxuefu** [smart-test-ti/SoloX#50]
![_20220824221117](https://user-images.githubusercontent.com/110112170/186441360-f622b01c-8c8f-44e0-a062-9c1583136022.png)
不加 -ef ,不显示当前进程list
C:\Users\Administrator>adb -s 195 shell ps | findstr tv.danmaku.bili

C:\Users\Administrator>adb -s 195 shell ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
shell        20536 23106 2260928   3704 0                   0 R ps

C:\Users\Administrator>adb -s 195 shell ps -ef| findstr tv.danmaku.bili
u0_a306      19253   859 14 21:53:06 ?    00:01:35 tv.danmaku.bili

**Comment by rafa0128** [comment]
> ![_20220824221117](https://user-images.githubusercontent.com/110112170/186441360-f622b01c-8c8f-44e0-a062-9c1583136022.png) 不加 -ef ,不显示当前进程list C:\Users\Administrator>adb -s 195 shell ps | findstr tv.danmaku.bili
> 
> C:\Users\Administrator>adb -s 195 shell ps USER PID PPID VSZ RSS WCHAN ADDR S NAME shell 20536 23106 2260928 3704 0 0 R ps
> 
> C:\Users\Administrator>adb -s 195 shell ps -ef| findstr tv.danmaku.bili u0_a306 19253 859 14 21:53:06 ? 00:01:35 tv.danmaku.bili

嗯是个问题，应该要加-ef的，不加的话有些系统会只显示主要的进程，有兴趣提个pr吗？坑位给你留着？下个版本我合并进来

**Comment by rafa0128** [comment]
> ![_20220824221117](https://user-images.githubusercontent.com/110112170/186441360-f622b01c-8c8f-44e0-a062-9c1583136022.png) 不加 -ef ,不显示当前进程list C:\Users\Administrator>adb -s 195 shell ps | findstr tv.danmaku.bili
> 
> C:\Users\Administrator>adb -s 195 shell ps USER PID PPID VSZ RSS WCHAN ADDR S NAME shell 20536 23106 2260928 3704 0 0 R ps
> 
> C:\Users\Administrator>adb -s 195 shell ps -ef| findstr tv.danmaku.bili u0_a306 19253 859 14 21:53:06 ? 00:01:35 tv.danmaku.bili

已经修复，请拉取最新代码，如果解决了的话，帮忙star一下哈
