### ISSUE TITLE
【BUG】CPU数据出现负数

### ISSUE THREAD

**Issue by partofme93** [smart-test-ti/SoloX#51]
测试机型：红米k50
系统版本：Android 12
测试APP： 斗鱼直播APP
测试环节：开播

异常现象：CPU数据出现负数，并且数值异常

异常截图：
![image](https://user-images.githubusercontent.com/51112273/186593519-239baa89-52ca-4b47-a1e4-a36007aa717f.png)

还麻烦开发者大佬帮排查看看可能是什么原因，谢谢~

**Comment by rafa0128** [comment]
> 测试机型：红米k50 系统版本：Android 12 测试APP： 斗鱼直播APP 测试环节：开播
> 
> 异常现象：CPU数据出现负数，并且数值异常
> 
> 异常截图： ![image](https://user-images.githubusercontent.com/51112273/186593519-239baa89-52ca-4b47-a1e4-a36007aa717f.png)
> 
> 还麻烦开发者大佬帮排查看看可能是什么原因，谢谢~

可以把report文件夹的数据打包传上来看一下，在你启动solox的目录
