### ISSUE TITLE
fps = apm.collectFps()  # HZ 采集数据为0

### ISSUE THREAD

**Issue by peterZhang000** [smart-test-ti/SoloX#53]
for line in results:
                if not isHaveFoundWindow:
                    if "Window" in line and self.focus_window in line:
                        isHaveFoundWindow = True  修改为：
           for line in results:
                if not isHaveFoundWindow:
                    if  self.focus_window in line:
                        isHaveFoundWindow = True 可以采集到数据，不过一直是60

**Comment by rafa0128** [comment]
如果感兴趣可以提PR就更好哈
