### ISSUE TITLE
诚挚征集新功能

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#59]
SoloX已经开发到一个比较成熟的阶段啦，个人想法有限，所以想征集一下大家的想法，结合大家的实际需求再继续丰富功能。

**Comment by yi122144453** [comment]
1、FPS的采集目前数据准确性和可靠性存在比较大的争议，是否可以优化一下该部分的功能？
2、是否可以支持多台设备同时采样数据，并进行数据对比分析或者Android&IOS跨平台的数据对比？

**Comment by rafa0128** [comment]
> 1、FPS的采集目前数据准确性和可靠性存在比较大的争议，是否可以优化一下该部分的功能？ 2、是否可以支持多台设备同时采样数据，并进行数据对比分析或者Android&IOS跨平台的数据对比？

1、fps会优化的，还在不断测试不同机型、不同app，会尽量给视频类、游戏类的app提供准确的数据
2、这个想法不错，支持同一设备，不同app对比；同一app，相同平台不同系统的设备对比；这个接下来安排。android和ios对比没太大必要，平台的系统机制都不一样了，没有可比性。

**Comment by rafa0128** [comment]
已经支持了不同设备和不同APP的对比模式，在首页「PK Model」入口

**Comment by hotoday** [comment]
NB，先用下试试！

**Comment by partofme93** [comment]
你好，请问下如何规范提pr加入开源，可以做一个简单的示例～

**Comment by yi122144453** [comment]
再给提一点小建议哈！report和实时监控页面建议把监控数据最大值、最小值、平均值和中位数等数据分析加进来提供更加明细的数据统计分析，目前平台只有平均值数据哦

**Comment by rafa0128** [comment]
> 你好，请问下如何规范提pr加入开源，可以做一个简单的示例～

这里还没想过，后续再找时间出一下吧，如果发现问题或者想增加功能随时可以提PR，但是比较大的改动话建议先邮件跟我聊清楚rafacheninc@gmail.com，深入了解了代码能力、对我们开源项目的兴趣后，会邀请成为开发者，后续一起不断推出有意思的开源项目。

**Comment by rafa0128** [comment]
> 再给提一点小建议哈！report和实时监控页面建议把监控数据最大值、最小值、平均值和中位数等数据分析加进来提供更加明细的数据统计分析，目前平台只有平均值数据哦

嗯这个有点必要，后面的版本加上吧，界面可能要看看怎么调
