### ISSUE TITLE
fps收集不准确的反馈

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#61]
请提供测试信息：手机品牌、系统版本、被测app

**Comment by yi122144453** [comment]
华为mate 40 Pro  鸿蒙OS 2.0.0.263   被测应用自研demo APP暂未发布上线     我手上的几个华为手机好像FPS都采集不到数据

**Comment by rafa0128** [comment]
> 华为mate 40 Pro 鸿蒙OS 2.0.0.263 被测应用自研demo APP暂未发布上线 我手上的几个华为手机好像FPS都采集不到数据

你好，我的也是鸿蒙系统的，测起来感觉很正常。先确定下达到以下条件了吗：
1、被测app界面是动态的？
2、GPU 呈现模式，选择“在adb shell dumpsys gfxinfo”

**Comment by rafa0128** [comment]
再补充一下：如果你们的fps比较小，请检查界面是否是动态的，就算是一些视频和直播，也可能界面变化不大，所以你们选择素材去测试时，最好要选择一个相对动态比较明显的数据。

**Comment by yi122144453** [comment]
> > 华为mate 40 Pro 鸿蒙OS 2.0.0.263 被测应用自研demo APP暂未发布上线 我手上的几个华为手机好像FPS都采集不到数据
> 
> 你好，我的也是鸿蒙系统的，测起来感觉很正常。先确定下达到以下条件了吗： 1、被测app界面是动态的？ 2、GPU 呈现模式，选择“在adb shell dumpsys gfxinfo”

1、被测APP界面是动态的，我们现在想监测的是实时视频通话的时候FPS情况，目前工具在这块的检测数据遇到了阻碍
2、GPU模式是开启的

**Comment by rafa0128** [comment]
> 请问下，是无法收集游戏类的FPS吗，问题如下： 如题，GPU呈现模式已打开（adb。。 gfxinfo） 试了小米6（安卓8系统），iqoo Neo5 SE（安卓12系统），华为P40pro（鸿蒙2.0），，跑的一款cocos2d x 游戏 FPS一直显示为零，其它数据能正常捕捉到

是的，>安卓8.0版本手机的还没支持收集游戏类应用fps，不同设备会有很大的兼容问题，还没找到特别好的方法

**Comment by MiniGrayGay** [comment]
红米K50至尊版，安卓12&Miui13.0.5，一把王者荣耀下来全程显示12fps，游戏里面是120
![report](https://user-images.githubusercontent.com/64829926/192891339-36226881-dad7-4a2e-a6b1-ca4b12df596c.png)

**Comment by gradient30** [comment]
安卓8.0及以上版本（针对游戏类产品） 作者明确回复了，目前无法收集- -，，在想其它办法


SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 凌晨5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] fps收集不准确的反馈 (Issue #61)





 
红米K50至尊版，安卓12&amp;Miui13.0.5，一把王者荣耀下来全程显示12fps，游戏里面是120

**Comment by rafa0128** [comment]
> 红米K50至尊版，安卓12&Miui13.0.5，一把王者荣耀下来全程显示12fps，游戏里面是120 ![report](https://user-images.githubusercontent.com/64829926/192891339-362目前采用的也是surfaceview的方式和perfdog一样，

> 红米K50至尊版，安卓12&Miui13.0.5，一把王者荣耀下来全程显示12fps，游戏里面是120 ![report](https://user-images.githubusercontent.com/64829926/192891339-36226881-dad7-4a2e-a6b1-ca4b12df596c.png)

之前才用了和perfdog一样的计算方法通过surface view计算，但是很多设备这个数据更新特别慢一直都是0，不知道perfdog收集会不会碰到这个问题，如果有条件可以帮忙对比一下。目前solox的fps计算的是界面操作滑动的流畅度

**Comment by gradient30** [comment]
https://github.com/vinjn/perf-doctor


这个可以收集到游戏的FPS，代码不是太懂，不知道有参考价值不




SunTM&amp;R
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunTM&amp;R"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 上午10:10
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [smart-test-ti/SoloX] fps收集不准确的反馈 (Issue #61)





安卓8.0及以上版本（针对游戏类产品） 作者明确回复了，目前无法收集- -，，在想其它办法


SunTM&amp;R
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "smart-test-ti/SoloX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 凌晨5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [smart-test-ti/SoloX] fps收集不准确的反馈 (Issue #61)





 
红米K50至尊版，安卓12&amp;Miui13.0.5，一把王者荣耀下来全程显示12fps，游戏里面是120
