### ISSUE TITLE
【Feature】输出的折线图每10s才进行一次绘制，间隔过于长了，能否优化至1-2s

### ISSUE THREAD

**Issue by morningofowl** [smart-test-ti/SoloX#69]
输出的折线图每10s才进行一次绘制，间隔过于长了，能否优化至1-2s

**Comment by rafa0128** [comment]
> 输出的折线图每10s才进行一次绘制，间隔过于长了，能否优化至1-2s

基本就是每秒都更新数据的，应该是终端性能跟不上了，建议换一下终端试试
windows：https://github.com/microsoft/terminal
mac：https://iterm2.com/

**Comment by morningofowl** [comment]
> 

<img width="776" alt="image" src="https://user-images.githubusercontent.com/20981135/191652309-270b5305-d7a7-456e-b43c-809e2e76c7ca.png">
可能理解有偏差，我说的是浏览器上的这个折线图，不是终端的输出

**Comment by rafa0128** [comment]
> > 
> 
> <img alt="image" width="776" src="https://user-images.githubusercontent.com/20981135/191652309-270b5305-d7a7-456e-b43c-809e2e76c7ca.png">
> 
> 可能理解有偏差，我说的是浏览器上的这个折线图，不是终端的输出

就是这个，因为多进程收集指标会吃性能一点，在一些终端里面会撑不住，我的在IDE里面跑也很慢的，找一些专门做终端的软件跑试试，solox是每2秒收集一次

**Comment by morningofowl** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="776" src="https://user-images.githubusercontent.com/20981135/191652309-270b5305-d7a7-456e-b43c-809e2e76c7ca.png">
> > 可能理解有偏差，我说的是浏览器上的这个折线图，不是终端的输出
> 
> 就是这个，因为多进程收集指标会吃性能一点，在一些终端里面会撑不住，我的在IDE里面跑也很慢的，找一些专门做终端的软件跑试试，solox是每2秒收集一次

哦哦，意思就是我的命令需要在你推荐的item2中试试是吧，因为采集的数据是吃性能的，最终呈现在浏览器中的数据展示也是受这个数据采集的影响
