### ISSUE TITLE
【BUG】Android cpu 占用和top命令获取的正好差了2倍，soloX获取的数据为top命令获取的1/2

### ISSUE THREAD

**Issue by morningofowl** [smart-test-ti/SoloX#71]
Android cpu 占用和top命令获取的正好差了2倍，soloX获取的数据为top命令获取的1/2

**Comment by rafa0128** [comment]
> Android cpu 占用和top命令获取的正好差了2倍，soloX获取的数据为top命令获取的1/2

用top如果是多核的设备，总的占用率可以超过100%，查看你的安卓机是几核的，除以你的核数，我这里限制了不超过100%来计算的，这个也是可以的

**Comment by morningofowl** [comment]
> > Android cpu 占用和top命令获取的正好差了2倍，soloX获取的数据为top命令获取的1/2
> 
> 用top如果是多核的设备，总的占用率可以超过100%，查看你的安卓机是几核的，除以你的核数，我这里限制了不超过100%来计算的，这个也是可以的

是已经除以了核数之后，soloX获取的数据为top命令获取的1/2

**Comment by rafa0128** [comment]
> > > Android cpu 占用和top命令获取的正好差了2倍，soloX获取的数据为top命令获取的1/2
> > 
> > 
> > 用top如果是多核的设备，总的占用率可以超过100%，查看你的安卓机是几核的，除以你的核数，我这里限制了不超过100%来计算的，这个也是可以的
> 
> 是已经除以了核数之后，soloX获取的数据为top命令获取的1/2，有个工具叫SoloPi，你这个获取出来的也是SoloPi的1/2
> 
> ```
> def getcpu(package):
>     li = os.popen("adb shell top -m 100 -n 1").readlines()
>     name = package
>     for line in li:
>         # 获取cpu的核心数，800%cpu   7%user   0%nice 103%sys 686%idle   0%iow   3%irq   0%sirq   0%host
>         if re.findall('%cpu', line):
>             cpu_num = int(line.split(" ")[0].split('%')[0])/100
>             print('本设备的cpu的核心数是：'+ str(cpu_num))
>         if re.findall(name, line):
>             cuplist = line.split(" ")
>             if cuplist[-1].strip() == package:
>                 while '' in cuplist:  # 将list中的空元素删除
>                     cuplist.remove('')
>                 # print(float(cuplist[8])/8)
>                 cpu_apk = str(float(cuplist[-4])/cpu_num) + '%' #此处需要除以cpu的核数
>                 print('该应用cpu的占用率是：' + str(cpu_apk))
>                 return cpu_apk  # 去掉百分号，返回一个float
> ```

嗯，看了下代码应该分子算小，下个版本修复
