### ISSUE TITLE
iOS16好像用不了了，前几天iOS15的时候还能正常使用的，点击start提示如下的错误

### ISSUE THREAD

**Issue by fairy-ju** [smart-test-ti/SoloX#72]
![QQ截图20220923193532](https://user-images.githubusercontent.com/84318632/191952426-76135458-0576-4914-be16-1d57dbdc785f.png)

**Comment by fairy-ju** [comment]
如果作者测试iOS16正常的话那就没事了，回头我再回去检查一下环境

**Comment by rafa0128** [comment]
> 如果作者测试iOS16正常的话那就没事了，回头我再回去检查一下环境

之前试过16也是支持的，你之前有没有自己装过tidevices？有的话卸载了重装一下solox

**Comment by Jason0Best** [comment]
> > 如果作者测试iOS16正常的话那就没事了，回头我再回去检查一下环境
> 
> 之前试过16也是支持的，你之前有没有自己装过tidevices？有的话卸载了重装一下solox

我这边也不行，iPhone XS，iOS16.1公测版，点击start可以开始但无法读出任何数据

**Comment by fairy-ju** [comment]
> tidevices

我还专门用tidevices命令行手动读取了一下功耗，也试了下tidevices一些其他指令，发现很多指令都失效了，不知道是我电脑的问题还是iOS的问题，但之前iOS15的时候就一切正常，但作者测试的iOS16没有问题我感觉应该是不会有问题的，tidevices本来就是基于XCode的调试，XCode也没更新没理由说用不了

**Comment by fairy-ju** [comment]
> > tidevices
> 
> 我还专门用tidevices命令行手动读取了一下功耗，也试了下tidevices一些其他指令，发现很多指令都失效了，不知道是我电脑的问题还是iOS的问题，但之前iOS15的时候就一切正常，但作者测试的iOS16没有问题我感觉应该是不会有问题的，tidevices本来就是基于XCode的调试，XCode也没更新没理由说用不了

tidevices其他指令失效也是提示的ImageMountFailed

**Comment by fairy-ju** [comment]
> > > 如果作者测试iOS16正常的话那就没事了，回头我再回去检查一下环境
> > 
> > 
> > 之前试过16也是支持的，你之前有没有自己装过tidevices？有的话卸载了重装一下solox
> 
> 我这边也不行，iPhone XS，iOS16.1公测版，点击start可以开始但无法读出任何数据

你之前iOS15的时候有用过吗，你那边iOS15正常吗

**Comment by Jason0Best** [comment]
> > > > 如果作者测试iOS16正常的话那就没事了，回头我再回去检查一下环境
> > > 
> > > 
> > > 之前试过16也是支持的，你之前有没有自己装过tidevices？有的话卸载了重装一下solox
> > 
> > 
> > 我这边也不行，iPhone XS，iOS16.1公测版，点击start可以开始但无法读出任何数据
> 
> 你之前iOS15的时候有用过吗，你那边iOS15正常吗

没试过。手上也没有iOS15的设备了，没法试。

**Comment by rafa0128** [comment]
> 

我刚试了ios16可以收集，tidevices能用这里就能用，检查一下环境吧

**Comment by GHOSTCui** [comment]
iOS 16新增了开发者模式，需手动打开

**Comment by Jason0Best** [comment]
> iOS 16新增了开发者模式，需手动打开

请问如何打开？我现在是iOS16.1 beta5，按照网上描述的隐私与安全性-安全性目录下仅有锁定模式而无开发者模式选项。

**Comment by GHOSTCui** [comment]
> > iOS 16新增了开发者模式，需手动打开
> 
> 请问如何打开？我现在是iOS16.1 beta5，按照网上描述的隐私与安全性-安全性目录下仅有锁定模式而无开发者模式选项。

大致过程是用数据线连电脑，然后在 Xcode 中激活，网上是有具体教程的

**Comment by fairy-ju** [comment]
> > 
> 
> 我刚试了ios16可以收集，tidevices能用这里就能用，检查一下环境吧

解决了，确实是iOS16新出的开发者模式的原因，把那个选项打开之后就能采集到数据了
