### ISSUE TITLE
IPhone 14 Pro 120fps? 偵測不到120fps

### ISSUE THREAD

**Issue by 309ehw** [smart-test-ti/SoloX#75]
如標題
![image](https://user-images.githubusercontent.com/58882447/194715393-3c7ceeb0-b2f6-4827-89aa-c1ef7431969d.png)

要怎麼做才能偵測到正確的fps，最近在測試原神搭配散熱器下的表現

IOS VERSION : IOS16.0.2

**Comment by rafa0128** [comment]
> 如標題 ![image](https://user-images.githubusercontent.com/58882447/194715393-3c7ceeb0-b2f6-4827-89aa-c1ef7431969d.png)
> 
> 要怎麼做才能偵測到正確的fps，最近在測試原神搭配散熱器下的表現
> 
> IOS VERSION : IOS16.0.2

solox只是用来发现问题的，不是用来解决怎么跑到120。首先游戏设置了120的帧率不代表一定能跑到120，有可能会丢帧，还有你的设备硬件条件的天花板是不是也有限制都是有影响的。你可以查一下iphone14 pro别人的评测的情况是怎么样的。

**Comment by 309ehw** [comment]
其他人是用perfdog去測試的，可以正確看到FPS會超過60

**Comment by rafa0128** [comment]
> 其他人是用perfdog去測試的，可以正確看到FPS會超過60



> 其他人是用perfdog去測試的，可以正確看到FPS會超過60

你能用perfdog测你那台设备吗？我看基本是很难跑到120的

**Comment by Jason0Best** [comment]
> > 其他人是用perfdog去測試的，可以正確看到FPS會超過60
> 
> > 其他人是用perfdog去測試的，可以正確看到FPS會超過60
> 
> 你能用perfdog测你那台设备吗？我看基本是很难跑到120的

我没有开发经验，不过根据以前测试游戏帧数的经验，如果不是他忘记开120帧或者游戏没适配的话，我觉得可能是solo X测量帧数的实现方法不太完善，在某个环节默认了最大60hz。
因为他的帧数是几乎是一条直线，如果是因为性能不足以跑到60帧以上，那肯定会是上下浮动的状态。只有设备本身的性能远超跑60帧的需求，却因为某些原因被限制在60帧（例如solo X无法显示60帧以上，或者他忘记在游戏里开120帧，或者原神还未适配iPhone14），才会出现贴着60hz跑成一条线的情况。如果开发者手里没有高刷苹果设备，个人也建议找设备来实际测试一下是否可用，以排除这位先生/女士潜在的自身失误因素。
