### ISSUE TITLE
关于FPS

### ISSUE THREAD

**Issue by rafa0128** [smart-test-ti/SoloX#79]
安卓：计算界面滑动的fps，>8.0系统的手机不支持游戏类的APP，视频类的APP也会有兼容问题。
iOS：xcode instruments的数据，有质疑数据不准确的，自己先用xcode比对一下。

**Comment by rafa0128** [comment]
https://bbs.perfdog.qq.com/?m=app&c=detail&a=index&id=201
看了perfdog的计算方法，用SurfaceView来计算的，但是我自己测试起来很多机器是没有更新数据的，除非perfdog不是用adb的方式获取。有了解的朋友可以给点意见。

**Comment by morningofowl** [comment]
> https://bbs.perfdog.qq.com/?m=app&c=detail&a=index&id=201 看了perfdog的计算方法，用SurfaceView来计算的，但是我自己测试起来很多机器是没有更新数据的，除非perfdog不是用adb的方式获取。有了解的朋友可以给点意见。

这个问题解决了吗
