### ISSUE TITLE
BUG：小米手机（设备信息：10S，Android12，MIUI13）在solox2.30版本运行监测cpu不正确

### ISSUE THREAD

**Issue by Aceyuan361** [smart-test-ti/SoloX#81]
操作步骤：
我使用小米10S使用手机直播软件进行手机投屏推流，然后使用solox进行监测，cpu的应用占用率一直在1%以下为主，内存占用也不对，这是明显不可能这么低，一般是去到10%左右的cpu占用率，500MB左右的运行内存，建议大佬看看。
![image](https://user-images.githubusercontent.com/110164764/197578926-fc31e275-66b5-4962-80c4-a7a6b7df19e1.png)

**Comment by rafa0128** [comment]
更新最新版本，你这个版本看上去是2.3.0之前的

**Comment by Aceyuan361** [comment]
> 更新最新版本，你这个版本看上去是2.3.0之前的

![image](https://user-images.githubusercontent.com/110164764/197714725-5fe05210-70a1-40d8-829a-381f6f358e1f.png)
是2.30的哦

**Comment by Aceyuan361** [comment]
> 更新最新版本，你这个版本看上去是2.3.0之前的

![image](https://user-images.githubusercontent.com/110164764/197714908-4a9d65dc-d15e-4bae-9b82-ed06ddc3435c.png)
是2.30的

**Comment by rafa0128** [comment]
> > 更新最新版本，你这个版本看上去是2.3.0之前的
> 
> ![image](https://user-images.githubusercontent.com/110164764/197714908-4a9d65dc-d15e-4bae-9b82-ed06ddc3435c.png) 是2.30的

用pip安装，现在最新版本是2.3.5
