### ISSUE TITLE
【BUG】windows连接 ios手机后，使用代码方式获取设备信息报错

### ISSUE THREAD

**Issue by cagezxy** [smart-test-ti/SoloX#87]
PC: win 10
device: ios 16,   iphone x

使用此方式链接手机
apm = APM(pkgName='com.xxxx', platform='iOS')

报错：
Traceback (most recent call last):
  File "F:\myproject2\solox\123123.py", line 4, in <module>
    apm = APM(pkgName='com.gddsssssxxxxx', platform='iOS')
  File "F:\myproject2\solox\solox\public\apm.py", line 297, in __init__
    d._devicesCheck(pf=self.platform, id=self.deviceId, pkg=self.pkgName)
  File "F:\myproject2\solox\solox\public\common.py", line 117, in _devicesCheck
    if len(self.getDeviceInfoByiOS()) == 0:
  File "F:\myproject2\solox\solox\public\common.py", line 93, in getDeviceInfoByiOS
    deviceResult = json.loads(self.execCmd('tidevice list --json'))
  File "D:\python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 3)

单独通过tidevice返回信息都是正常的。
通过查看：
返回的 设备信息时，最后换行中带了 无法解析的内容，导致 json.loads 时报错
![image](https://user-images.githubusercontent.com/30433065/203491532-a42ad223-7cec-4fc5-8ae8-fb7de1f4c1b8.png)

麻烦查看，是否有此问题

**Comment by rafa0128** [comment]
> raise JSONDecodeError("Extra data", s, end)

≈

**Comment by cagezxy** [comment]
> ![image](https://user-images.githubusercontent.com/24454096/203517625-edecb613-ab1a-4126-b988-6539667c8c4a.png) 麻烦贴完整的文本看看

['[\n', '    {\n', '        "udid": "8af88*******5",\n', '        "serial": "F1*******F",\n', '        "name": "娴嬭瘯缁勭殑x",\n', '        "market_name": "iPhone X",\n', '        "product_version": "16.1",\n', '        "conn_type": "usb"\n', '    }\n', ']\n', '\x1b[0m']
