### ISSUE TITLE
手机无法链接

### ISSUE THREAD

**Issue by OhyeahManTou** [smart-test-ti/SoloX#88]
手机通过adb devices看能打印出来手机信息，可是就一直链接不上是什么原因
界面链接上有较多304 和这个有关系吗，感谢！

**Comment by rafa0128** [comment]
> 手机通过adb devices看能打印出来手机信息，可是就一直链接不上是什么原因 界面链接上有较多304 和这个有关系吗，感谢！

如果是安卓的话，连不上只能是adb的问题，如果你的环境变量配置好adb，那么就用你的电脑自带的adb，如果没有就用SoloX自带的，但不一定适配你的电脑。麻烦你终端打adb devices截图传上来看看

**Comment by OhyeahManTou** [comment]
![image](https://user-images.githubusercontent.com/26593706/205530459-1d6aa535-5ac2-485f-b18d-cb742bd6afc7.png)

大概是这样

**Comment by OhyeahManTou** [comment]
我尝试升级了下adb的版本，升到最新的就解决了，感谢感谢！！
