### ISSUE TITLE
get network data failed : 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Jinggit** [smart-test-ti/SoloX#89]
C:\Users\jingg>python -m solox
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
[I 221207 14:28:18 web:141] start solox server...
 * Serving Flask app 'solox.web' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://10.0.0.191:50003/ (Press CTRL+C to quit)
10.0.0.191 - - [07/Dec/2022 14:28:18] "GET / HTTP/1.1" 200 -
[I 221207 14:28:18 web:144] Running on http://10.0.0.191:50003/?platform=Android (Press CTRL+C to quit)
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /?platform=Android HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/tabler.demo.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/tabler.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/sweetalert2.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/highlight.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2-bootstrap-5-theme.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2-bootstrap-5-theme.rtl.min.css HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/tabler.demo.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/sweetalert2.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/tabler.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/apexcharts.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/highlight.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/select2.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/gray.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/logo/logo.png HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/image/coffee.png HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/socket.io.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/html2canvas.min.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/highstock.js HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:21] "GET /device/ids?platform=Android&_=1670441299869 HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:31] "GET /device/ids?platform=Android&_=1670441299870 HTTP/1.1" 200 -
10.0.0.191 - - [07/Dec/2022 14:28:47] "POST /apm/initialize HTTP/1.1" 200 -
[E 221207 14:28:47 apis:129] get cpu failed : list index out of range
10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/cpu?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299871 HTTP/1.1" 200 -
[E 221207 14:28:47 apis:197] get network data failed : 'NoneType' object has no attribute 'group'
10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/network?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299873 HTTP/1.1" 200 -
[E 221207 14:28:47 apis:163] get memory data failed : 'NoneType' object has no attribute 'group'
10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/mem?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299872 HTTP/1.1" 200 -

**Comment by rafa0128** [comment]
> C:\Users\jingg>python -m solox WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance. [I 221207 14:28:18 web:141] start solox server...
> 
> * Serving Flask app 'solox.web' (lazy loading)
> * Environment: production
>   WARNING: This is a development server. Do not use it in a production deployment.
>   Use a production WSGI server instead.
> * Debug mode: off
> * Running on http://10.0.0.191:50003/ (Press CTRL+C to quit)
>   10.0.0.191 - - [07/Dec/2022 14:28:18] "GET / HTTP/1.1" 200 -
>   [I 221207 14:28:18 web:144] Running on http://10.0.0.191:50003/?platform=Android (Press CTRL+C to quit)
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /?platform=Android HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/tabler.demo.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/tabler.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/sweetalert2.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/highlight.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2-bootstrap-5-theme.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/css/select2-bootstrap-5-theme.rtl.min.css HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/tabler.demo.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/sweetalert2.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/tabler.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/jquery.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/apexcharts.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/highlight.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/select2.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/gray.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/logo/logo.png HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/image/coffee.png HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/socket.io.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/html2canvas.min.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:19] "GET /static/js/highstock.js HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:21] "GET /device/ids?platform=Android&_=1670441299869 HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:31] "GET /device/ids?platform=Android&_=1670441299870 HTTP/1.1" 200 -
>   10.0.0.191 - - [07/Dec/2022 14:28:47] "POST /apm/initialize HTTP/1.1" 200 -
>   [E 221207 14:28:47 apis:129] get cpu failed : list index out of range
>   10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/cpu?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299871 HTTP/1.1" 200 -
>   [E 221207 14:28:47 apis:197] get network data failed : 'NoneType' object has no attribute 'group'
>   10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/network?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299873 HTTP/1.1" 200 -
>   [E 221207 14:28:47 apis:163] get memory data failed : 'NoneType' object has no attribute 'group'
>   10.0.0.191 - - [07/Dec/2022 14:28:47] "GET /apm/mem?platform=Android&pkgname=com.buildingstack.bstkmobile&device=LGD8529221e2c7(LG-D852)&_=1670441299872 HTTP/1.1" 200 -

是每次出现还是执行过程中偶尔出现？一版是设备断连了会出现这种情况
