### ISSUE TITLE
可否打一个完整的exe程序，这样就不需要安装各种库了

### ISSUE THREAD

**Issue by qwz160** [smart-test-ti/SoloX#91]
可否打一个完整的exe程序，这样就不需要安装各种库了，麻烦打个exe程序，谢谢了

**Comment by rafa0128** [comment]
> 可否打一个完整的exe程序，这样就不需要安装各种库了，麻烦打个exe程序，谢谢了

有python3环境就行了，做客户端要适配各个平台成本太大
