### ISSUE TITLE
请教 图表如何集成到jenkins ? 

### ISSUE THREAD

**Issue by fanlb** [smart-test-ti/SoloX#92]
最开始想到的是在excel中生成折线图 在上传jenkins , 但发现excel中的折线图显示不全
问一下 solox中的图表用什么库生成的? 可以集成到jenkins中吗?

**Comment by rafa0128** [comment]
> 最开始想到的是在excel中生成折线图 在上传jenkins , 但发现excel中的折线图显示不全 问一下 solox中的图表用什么库生成的? 可以集成到jenkins中吗?

首页是用highcharts，报告页用apexcharts。集成到Jenkins我理解你自己写脚本调用solox的api就行了

**Comment by fanlb** [comment]
最终还是写入到excel中 , 多谢回复
