### ISSUE TITLE
连接 iPad 报错

### ISSUE THREAD

**Issue by kawaiisurfer** [smart-test-ti/SoloX#93]
连上了，游戏开了，图一直出不来
纯小白，真的不太懂，跪求大佬封装出exe
<img width="1496" alt="屏幕截图 2022-12-17 192204" src="https://user-images.githubusercontent.com/104144911/208239338-d1a7864b-1c3a-482a-a980-f63e00bbfcb7.png">

**Comment by rafa0128** [comment]
请更新一下solox的新版本，你在本地打这个命令：tidevice list，发上来看看
