### ISSUE TITLE
本地不能打印logcat日志的问题

### ISSUE THREAD

**Issue by jiapeng320515** [smart-test-ti/SoloX#95]
你好，
使用python3 -m solox --host=0.0.0.0 --port=50003  命令启动服务器开始监听手机后在./adblog 中没有任何日志输出，控制台有如下报错
"GET /socket.io/?EIO=3&transport=polling&t=1671692366246-26 HTTP/1.1" 400

**Comment by rafa0128** [comment]
> 你好， 使用python3 -m solox --host=0.0.0.0 --port=50003 命令启动服务器开始监听手机后在./adblog 中没有任何日志输出，控制台有如下报错 "GET /socket.io/?EIO=3&transport=polling&t=1671692366246-26 HTTP/1.1" 400

这不是报错，logcat要打开error log开关，只收集错误信息
