### ISSUE TITLE
[BUG] IOS 16.2支持有问题

### ISSUE THREAD

**Issue by R-umia** [smart-test-ti/SoloX#97]
get memory data failed : 404 Client Error: Not Found for url: https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/16.2.zip

**Comment by rafa0128** [comment]
> https://tool.appetizer.io/JinjunHan/iOSDeviceSupport/raw/master/DeviceSupport/16.2.zip

现在应该没有问题了吧？
