### ISSUE TITLE
BUG：荣耀手机FPS异常（设备信息：荣耀畅玩20，Android10，MagicUI 4.0）在solox2.3.7版本运行监测FPS不正确 #81

### ISSUE THREAD

**Issue by Tcyily** [smart-test-ti/SoloX#99]
![image](https://user-images.githubusercontent.com/31086836/212028152-281e918a-39e8-4475-bf70-98b600f5cdc6.png)
游戏体验下来是正常游玩的

**Comment by rafa0128** [comment]
游戏类app暂时还没有办法收集fps
